### ISSUE TITLE
Filter /api/v2/views by view type

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/platform#1003]
As a follow up to #918 the logs page needs an endpoint that returns some log page struct that contains a single view of type `log-viewer`. Making a `GET /api/v2/log` could either find or create the log page with a [default log viewer view](https://github.com/influxdata/chronograf/blob/2f2263d7acbbac16e0cc4d5ef6e48775678993c5/bolt/org_config.go#L90-L234) similar to the `org_config` endpoint in chronograf.

**Comment by goller** [comment]
Let's add filtering of view types.  This allows us to have multiple log-viewers in the future

**Comment by goller** [comment]
I'm thinking `/api/v2/views?type=foo&type=bar` to return 2 types of views.
