### ISSUE TITLE
Task update never works

### ISSUE THREAD

**Issue by bthesorceror** [influxdata/platform#1067]
Trying to update a task that I just created with a payload that only includes a payload with status always returns an error of `task has already been claimed`

**Comment by mark-rushakoff** [comment]
I have a branch ready for this (https://github.com/influxdata/platform/tree/fix/task-only-update-status). Waiting on https://github.com/influxdata/platform/pull/975 to get merged first, with the expectation that I'll have some merge conflicts to deal with.
