### ISSUE TITLE
Tasks index endpoint does not return task statuses

### ISSUE THREAD

**Issue by bthesorceror** [influxdata/platform#1106]
When I make a request to the `api/v2/tasks` endpoint the list of tasks that I get back does not include the status.

**Comment by mark-rushakoff** [comment]
Here are the TODO and test that need to be updated as part of this fix: https://github.com/influxdata/platform/blob/ea4c08b327efa62f870eb95ee217361e232e56dc/task/servicetest/servicetest.go#L150-L155
