### ISSUE TITLE
Make transpilerd stub out the write endpoint

### ISSUE THREAD

**Issue by nathanielc** [influxdata/platform#122]

**Comment by jsternberg** [comment]
@goller is the plan for gatewayd to take care of this? It seems like we've moved on the idea that transpilerd isn't a user-facing service so I'm tempted to close this.

**Comment by goller** [comment]
@jsternberg I think it could be closed... @nathanielc was there anything transpiler specific that needed to happen there?  

We don't have support for all the options yet of /write.  Perhaps change this issue to review /write options and add them to gateway?

**Comment by nathanielc** [comment]
Closing issue as the transpiler API is now internal. There is no need to emulate the `/write` endpoint. If there are bugs/discrepancies in the existing `/write` endpoint on gateway those can be separate issues.
