### ISSUE TITLE
task: run retry should return newly created run data

### ISSUE THREAD

**Issue by goller** [influxdata/platform#1234]
Runs should return their resource on creation.  

```
-        '200':
-          description: The newly created retry run
-          content:
-            application/json:
-              schema:
-                $ref: "#/components/schemas/Run"
+        '204':
+          description: retry has been queued

```

**Comment by mark-rushakoff** [comment]
We can't make that guarantee. A retry does not synchronously create a new run. It enqueues a request for a new run, which the scheduler will pick up as soon as it can.

**Comment by goller** [comment]
@mark-rushakoff a run can be in the "scheduled" state:

https://github.com/influxdata/platform/blob/master/http/swagger.yml#L3584

The pattern should be 200 created with a JSON body response of the run like this:

```json
{
        "id": "12345678",
        "taskID": "12345678",
        "status": "scheduled",
        "requestedAt": "2018-10-30T20:54:21+00:00",
        "links": {
            "self": "/api/v2/tasks/12345678/runs/12345678"
        }
}
```

This signals that the run request has been created and is in the scheduled state.

The consumer of the API then is able to poll the self link and watch while the status progresses through "scheduled", "executing", and "success."

It is true that a retry would not synchronously create an "executing" run, but it does create a run that has been scheduled. 

Run in this case is a noun to me and not the state of running.

**Comment by mark-rushakoff** [comment]
I see what you're getting at. The implementation details right now are that a run is not assigned an ID until its execution begins. We don't have a persisted "scheduled" state for runs inside the task system. They're either nonexistent, started, succeeded, or failed.

What you're asking is doable, but it will take some effort.
