### ISSUE TITLE
Race detection

### ISSUE THREAD

**Issue by docmerlin** [influxdata/platform#13]
We should add race detection to tests in the CI suite here.
This ticket doesn't necessairly include fixing any races that crop up.

**Comment by sdomino** [comment]
Quick question. I noticed [here](https://github.com/influxdata/platform/blob/master/Makefile#L97) that there already appears to be a task for running the tests with `-race`.

Is the intention to change [this](https://github.com/influxdata/platform/blob/master/.circleci/config.yml#L11) to use that task, run it in addition to what's already there, or something else?

**Comment by docmerlin** [comment]
This was made at the same time as that.  I'll go ahead and close this as it seems redundant now.
