### ISSUE TITLE
bug: transpiler group by time 

### ISSUE THREAD

**Issue by jlapacik** [influxdata/platform#1336]
Given the following input data:

    {"results":[{"statement_id":0,"series":[{"name":"m","columns":["time","f","t"],"values":[["1970-01-01T00:00:00Z",0.21733540427389167,"0"],["1970-01-01T00:00:00Z",0.10048266021635104,"e"],["1970-01-01T00:00:00Z",0.5868723451342756,"1"],["1970-01-01T00:00:00Z",0.39487629241910327,"3"],["1970-01-01T00:00:00Z",0.44067909056188065,"7"],["1970-01-01T00:00:00Z",0.028960468596174082,"8"],["1970-01-01T00:00:00Z",0.5553418917929255,"4"],["1970-01-01T00:00:00Z",0.29873253087687857,"9"],["1970-01-01T00:00:00Z",0.4136032899577586,"a"],["1970-01-01T00:00:00Z",0.3527118913572553,"2"],["1970-01-01T00:00:00Z",0.5617602015706409,"5"],["1970-01-01T00:00:00Z",0.1109754416526329,"b"],["1970-01-01T00:00:00Z",0.4965122390144968,"c"],["1970-01-01T00:00:00Z",0.022853146138288635,"6"],["1970-01-01T00:00:00Z",0.6007250742557967,"d"],["1970-01-01T01:00:00Z",0.5480416564167807,"6"],["1970-01-01T01:00:00Z",0.005120363093301438,"d"],["1970-01-01T01:00:00Z",0.33401886401379766,"4"],["1970-01-01T01:00:00Z",0.40295528925252116,"1"],["1970-01-01T01:00:00Z",0.20688486498664724,"0"],["1970-01-01T01:00:00Z",0.8287168751261227,"e"],["1970-01-01T01:00:00Z",0.2623456405300397,"8"],["1970-01-01T01:00:00Z",0.8522520753875706,"3"],["1970-01-01T01:00:00Z",0.05266160797305602,"7"],["1970-01-01T01:00:00Z",0.7113603589265851,"c"],["1970-01-01T01:00:00Z",0.6182827000737869,"2"],["1970-01-01T01:00:00Z",0.9400135556878947,"9"],["1970-01-01T01:00:00Z",0.6232172394890676,"a"],["1970-01-01T01:00:00Z",0.6135176101300653,"b"],["1970-01-01T01:00:00Z",0.7727621737084356,"5"],["1970-01-01T02:00:00Z",0.22203933679920654,"b"],["1970-01-01T02:00:00Z",0.0026975246398492007,"5"],["1970-01-01T02:00:00Z",0.8256039611010968,"8"],["1970-01-01T02:00:00Z",0.6377103208277117,"4"],["1970-01-01T02:00:00Z",0.8830647189180069,"6"],["1970-01-01T02:00:00Z",0.037406357505062056,"d"],["1970-01-01T02:00:00Z",0.15138942969726804,"e"],["1970-01-01T02:00:00Z",0.4346048405305463,"1"],["1970-01-01T02:00:00Z",0.08156734861691889,"0"],["1970-01-01T02:00:00Z",0.5850725395017028,"a"],["1970-01-01T02:00:00Z",0.4953730904266219,"c"],["1970-01-01T02:00:00Z",0.025695763492424337,"3"],["1970-01-01T02:00:00Z",0.8398055035861259,"7"],["1970-01-01T02:00:00Z",0.8066372028594551,"9"],["1970-01-01T02:00:00Z",0.20708240051639593,"2"],["1970-01-01T03:00:00Z",0.21397110121120685,"9"],["1970-01-01T03:00:00Z",0.3784390684137637,"2"],["1970-01-01T03:00:00Z",0.9701634394842537,"e"],["1970-01-01T03:00:00Z",0.5881745371000942,"8"],["1970-01-01T03:00:00Z",0.1102813897277559,"b"],["1970-01-01T03:00:00Z",0.6245152286158625,"5"],["1970-01-01T03:00:00Z",0.0912721269371512,"d"],["1970-01-01T03:00:00Z",0.5674930799498789,"4"],["1970-01-01T03:00:00Z",0.37309538818717647,"6"],["1970-01-01T03:00:00Z",0.2500614093187628,"7"],["1970-01-01T03:00:00Z",0.2859330711319738,"a"],["1970-01-01T03:00:00Z",0.9474743233238748,"1"],["1970-01-01T03:00:00Z",0.7544881599195352,"0"],["1970-01-01T03:00:00Z",0.43256014611971805,"3"],["1970-01-01T03:00:00Z",0.7482955172190678,"c"],["1970-01-01T04:00:00Z",0.047410696851533915,"3"],["1970-01-01T04:00:00Z",0.29736065380095505,"c"],["1970-01-01T04:00:00Z",0.8780811914766983,"d"],["1970-01-01T04:00:00Z",0.27538705611851577,"e"],["1970-01-01T04:00:00Z",0.532119077812898,"9"],["1970-01-01T04:00:00Z",0.37360745207402807,"2"],["1970-01-01T04:00:00Z",0.45482238476124653,"5"],["1970-01-01T04:00:00Z",0.5252562947569832,"8"],["1970-01-01T04:00:00Z",0.17514386160239845,"b"],["1970-01-01T04:00:00Z",0.02264855451581553,"0"],["1970-01-01T04:00:00Z",0.3105782686399675,"7"],["1970-01-01T04:00:00Z",0.3221419982960781,"4"],["1970-01-01T04:00:00Z",0.7116291351347792,"6"],["1970-01-01T04:00:00Z",0.883868171992124,"1"],["1970-01-01T04:00:00Z",0.9944899118127165,"a"],["1970-01-01T05:00:00Z",0.9394309239047515,"1"],["1970-01-01T05:00:00Z",0.3486209115450334,"a"],["1970-01-01T05:00:00Z",0.18575386702759947,"5"],["1970-01-01T05:00:00Z",0.7455287946173157,"d"],["1970-01-01T05:00:00Z",0.21011396610819746,"3"],["1970-01-01T05:00:00Z",0.2803585963587263,"c"],["1970-01-01T05:00:00Z",0.9368169523008139,"2"],["1970-01-01T05:00:00Z",0.18513998518404623,"e"],["1970-01-01T05:00:00Z",0.04922557943839125,"9"],["1970-01-01T05:00:00Z",0.22811709406742683,"6"],["1970-01-01T05:00:00Z",0.31721618161553417,"0"],["1970-01-01T05:00:00Z",0.10228677938581453,"8"],["1970-01-01T05:00:00Z",0.2456920288676328,"b"],["1970-01-01T05:00:00Z",0.9152207779776016,"4"],["1970-01-01T05:00:00Z",0.3193039889381033,"7"],["1970-01-01T06:00:00Z",0.5510242664167347,"4"],["1970-01-01T06:00:00Z",0.5746730121492845,"7"],["1970-01-01T06:00:00Z",0.08472696652684564,"2"],["1970-01-01T06:00:00Z",0.6524187089581357,"5"],["1970-01-01T06:00:00Z",0.7863865565205209,"1"],["1970-01-01T06:00:00Z",0.4119270312121963,"a"],["1970-01-01T06:00:00Z",0.57820212305636,"c"],["1970-01-01T06:00:00Z",0.19806100498944165,"d"],["1970-01-01T06:00:00Z",0.6730418346101648,"3"],["1970-01-01T06:00:00Z",0.739315569082104,"b"],["1970-01-01T06:00:00Z",0.21597842385515803,"6"],["1970-01-01T06:00:00Z",0.8939781841816075,"e"],["1970-01-01T06:00:00Z",0.5318290576930456,"9"],["1970-01-01T06:00:00Z",0.3907890779009442,"8"],["1970-01-01T06:00:00Z",0.4979093449569009,"0"],["1970-01-01T07:00:00Z",0.2037739475570841,"8"],["1970-01-01T07:00:00Z",0.2033824902425029,"0"],["1970-01-01T07:00:00Z",0.04001813819424512,"c"],["1970-01-01T07:00:00Z",0.6518468054699785,"2"],["1970-01-01T07:00:00Z",0.1862890669054775,"4"],["1970-01-01T07:00:00Z",0.6843435036089457,"7"],["1970-01-01T07:00:00Z",0.7965621655565867,"a"],["1970-01-01T07:00:00Z",0.5339339702564813,"5"],["1970-01-01T07:00:00Z",0.22489092506758881,"1"],["1970-01-01T07:00:00Z",0.16951200725074253,"9"],["1970-01-01T07:00:00Z",0.8953215116194001,"b"],["1970-01-01T07:00:00Z",0.06541446307307137,"d"],["1970-01-01T07:00:00Z",0.03801816564843288,"3"],["1970-01-01T07:00:00Z",0.4979458048354386,"e"],["1970-01-01T07:00:00Z",0.4821158576641412,"6"],["1970-01-01T08:00:00Z",0.9892461372745025,"e"],["1970-01-01T08:00:00Z",0.584231974112091,"6"],["1970-01-01T08:00:00Z",0.6068264153515747,"a"],["1970-01-01T08:00:00Z",0.12837626686230666,"c"],["1970-01-01T08:00:00Z",0.5839996912252242,"8"],["1970-01-01T08:00:00Z",0.13397866450883703,"0"],["1970-01-01T08:00:00Z",0.4654168839347631,"7"],["1970-01-01T08:00:00Z",0.5450271323060157,"2"],["1970-01-01T08:00:00Z",0.6701297011490235,"4"],["1970-01-01T08:00:00Z",0.6803748068627958,"3"],["1970-01-01T08:00:00Z",0.5039544815854242,"9"],["1970-01-01T08:00:00Z",0.4659810490090824,"5"],["1970-01-01T08:00:00Z",0.1533065778694078,"1"],["1970-01-01T08:00:00Z",0.4049594998819063,"d"],["1970-01-01T08:00:00Z",0.10917253189655304,"b"],["1970-01-01T09:00:00Z",0.2784551687516651,"d"],["1970-01-01T09:00:00Z",0.09125752561755446,"b"],["1970-01-01T09:00:00Z",0.11543694875091151,"7"],["1970-01-01T09:00:00Z",0.9927597244610361,"a"],["1970-01-01T09:00:00Z",0.805622294587642,"e"],["1970-01-01T09:00:00Z",0.14915819095560842,"6"],["1970-01-01T09:00:00Z",0.5882444674964562,"0"],["1970-01-01T09:00:00Z",0.7216878433742528,"c"],["1970-01-01T09:00:00Z",0.5626999768176523,"8"],["1970-01-01T09:00:00Z",0.992611279736199,"1"],["1970-01-01T09:00:00Z",0.5355199791885639,"3"],["1970-01-01T09:00:00Z",0.24335751514782133,"2"],["1970-01-01T09:00:00Z",0.19676671809325275,"4"],["1970-01-01T09:00:00Z",0.749678773432426,"5"],["1970-01-01T09:00:00Z",0.1281354317311823,"9"],["1970-01-01T10:00:00Z",0.7806758386232006,"5"],["1970-01-01T10:00:00Z",0.9449338978167051,"9"],["1970-01-01T10:00:00Z",0.695516703370055,"0"],["1970-01-01T10:00:00Z",0.9356540904388493,"7"],["1970-01-01T10:00:00Z",0.5558712009753174,"d"],["1970-01-01T10:00:00Z",0.10510750316901417,"b"],["1970-01-01T10:00:00Z",0.6766074703294818,"6"],["1970-01-01T10:00:00Z",0.8234474129708177,"a"],["1970-01-01T10:00:00Z",0.2931297083699952,"e"],["1970-01-01T10:00:00Z",0.18889638533425257,"4"],["1970-01-01T10:00:00Z",0.12018815383972621,"1"],["1970-01-01T10:00:00Z",0.8246059260450553,"c"],["1970-01-01T10:00:00Z",0.9430419383270346,"8"],["1970-01-01T10:00:00Z",0.8930488352039893,"2"],["1970-01-01T10:00:00Z",0.4955337446591014,"3"],["1970-01-01T11:00:00Z",0.7657035517213573,"2"],["1970-01-01T11:00:00Z",0.06882760258342699,"3"],["1970-01-01T11:00:00Z",0.4268811017242283,"6"],["1970-01-01T11:00:00Z",0.0771255379334489,"0"],["1970-01-01T11:00:00Z",0.8114723505898784,"5"],["1970-01-01T11:00:00Z",0.34944386376909053,"9"],["1970-01-01T11:00:00Z",0.7255108551642446,"b"],["1970-01-01T11:00:00Z",0.781697122084025,"7"],["1970-01-01T11:00:00Z",0.5931918839126434,"d"],["1970-01-01T11:00:00Z",0.693634688012895,"8"],["1970-01-01T11:00:00Z",0.5287527649900249,"4"],["1970-01-01T11:00:00Z",0.452191402633699,"a"],["1970-01-01T11:00:00Z",0.4583032165623844,"e"],["1970-01-01T11:00:00Z",0.413477742081763,"c"],["1970-01-01T11:00:00Z",0.42596636609238636,"1"],["1970-01-01T12:00:00Z",0.0834557677022344,"c"],["1970-01-01T12:00:00Z",0.20629053251980545,"1"],["1970-01-01T12:00:00Z",0.5521711104487992,"b"],["1970-01-01T12:00:00Z",0.6768497244580937,"6"],["1970-01-01T12:00:00Z",0.3044956922809049,"2"],["1970-01-01T12:00:00Z",0.9793931103753881,"3"],["1970-01-01T12:00:00Z",0.41534855647166935,"9"],["1970-01-01T12:00:00Z",0.03956287543778644,"0"],["1970-01-01T12:00:00Z",0.15648283534336155,"5"],["1970-01-01T12:00:00Z",0.28882462419014526,"e"],["1970-01-01T12:00:00Z",0.002696344133019735,"8"],["1970-01-01T12:00:00Z",0.7132890161478107,"7"],["1970-01-01T12:00:00Z",0.02517401620384494,"d"],["1970-01-01T12:00:00Z",0.8724407210435515,"a"],["1970-01-01T12:00:00Z",0.7529672207040509,"4"],["1970-01-01T13:00:00Z",0.30870014185060696,"a"],["1970-01-01T13:00:00Z",0.3797919542877444,"4"],["1970-01-01T13:00:00Z",0.018099017011747938,"9"],["1970-01-01T13:00:00Z",0.0026168078865614667,"b"],["1970-01-01T13:00:00Z",0.5669800893469398,"c"],["1970-01-01T13:00:00Z",0.03318728158531121,"1"],["1970-01-01T13:00:00Z",0.34031413350567824,"3"],["1970-01-01T13:00:00Z",0.7987253405067182,"6"],["1970-01-01T13:00:00Z",0.1990911309489573,"2"],["1970-01-01T13:00:00Z",0.3874959183231833,"d"],["1970-01-01T13:00:00Z",0.5738530198410188,"e"],["1970-01-01T13:00:00Z",0.24417922788036966,"0"],["1970-01-01T13:00:00Z",0.1759302392409728,"5"],["1970-01-01T13:00:00Z",0.6588555893433918,"7"],["1970-01-01T13:00:00Z",0.4919815823362141,"8"],["1970-01-01T14:00:00Z",0.2688542446733399,"7"],["1970-01-01T14:00:00Z",0.6612739219430225,"8"],["1970-01-01T14:00:00Z",0.7346922725770435,"3"],["1970-01-01T14:00:00Z",0.9471839531969641,"9"],["1970-01-01T14:00:00Z",0.9359271506247674,"a"],["1970-01-01T14:00:00Z",0.7189696835875524,"4"],["1970-01-01T14:00:00Z",0.7648009055935913,"1"],["1970-01-01T14:00:00Z",0.09632558408787695,"b"],["1970-01-01T14:00:00Z",0.242022875345309,"c"],["1970-01-01T14:00:00Z",0.727158376219158,"5"],["1970-01-01T14:00:00Z",0.33185908372728606,"d"],["1970-01-01T14:00:00Z",0.4665805977306695,"6"],["1970-01-01T14:00:00Z",0.679039875986828,"2"],["1970-01-01T14:00:00Z",0.32096353435272723,"0"],["1970-01-01T14:00:00Z",0.8577246081782713,"e"],["1970-01-01T15:00:00Z",0.7725492459641561,"0"],["1970-01-01T15:00:00Z",0.7537364801081793,"e"],["1970-01-01T15:00:00Z",0.7068108429449903,"1"],["1970-01-01T15:00:00Z",0.7611592790209047,"3"],["1970-01-01T15:00:00Z",0.5755499215232929,"7"],["1970-01-01T15:00:00Z",0.8410856217746696,"8"],["1970-01-01T15:00:00Z",0.09070680451439052,"4"],["1970-01-01T15:00:00Z",0.16558652881758293,"9"],["1970-01-01T15:00:00Z",0.4493804037604358,"a"],["1970-01-01T15:00:00Z",0.8164937424803885,"2"],["1970-01-01T15:00:00Z",0.17106219684855434,"5"],["1970-01-01T15:00:00Z",0.8351893849316041,"b"],["1970-01-01T15:00:00Z",0.5768373158183521,"c"],["1970-01-01T15:00:00Z",0.16525244337018163,"6"],["1970-01-01T15:00:00Z",0.7001233324274201,"d"],["1970-01-01T16:00:00Z",0.18706103242593092,"6"],["1970-01-01T16:00:00Z",0.9702837285540719,"d"],["1970-01-01T16:00:00Z",0.26415324899900855,"4"],["1970-01-01T16:00:00Z",0.28295297564517985,"1"],["1970-01-01T16:00:00Z",0.2809727487526847,"0"],["1970-01-01T16:00:00Z",0.10236952049349575,"e"],["1970-01-01T16:00:00Z",0.6504223157942212,"8"],["1970-01-01T16:00:00Z",0.21811251602825504,"3"],["1970-01-01T16:00:00Z",0.6441810454122652,"7"],["1970-01-01T16:00:00Z",0.9605094927180056,"c"],["1970-01-01T16:00:00Z",0.014955583859277517,"2"],["1970-01-01T16:00:00Z",0.7933987881271853,"9"],["1970-01-01T16:00:00Z",0.3952979089259298,"a"],["1970-01-01T16:00:00Z",0.0691186777010207,"b"],["1970-01-01T16:00:00Z",0.273383553761641,"5"],["1970-01-01T17:00:00Z",0.7480386565613738,"b"],["1970-01-01T17:00:00Z",0.3894917410266775,"5"],["1970-01-01T17:00:00Z",0.3748725469185533,"8"],["1970-01-01T17:00:00Z",0.08676973239602584,"4"],["1970-01-01T17:00:00Z",0.14770797288610577,"6"],["1970-01-01T17:00:00Z",0.5983386627994249,"d"],["1970-01-01T17:00:00Z",0.7711350483905655,"e"],["1970-01-01T17:00:00Z",0.5993305164847005,"1"],["1970-01-01T17:00:00Z",0.5721963265036002,"0"],["1970-01-01T17:00:00Z",0.4572934798948432,"a"],["1970-01-01T17:00:00Z",0.2519873837046142,"c"],["1970-01-01T17:00:00Z",0.635626045823084,"3"],["1970-01-01T17:00:00Z",0.14547418224251257,"7"],["1970-01-01T17:00:00Z",0.6770483677906765,"9"],["1970-01-01T17:00:00Z",0.7634994943879522,"2"],["1970-01-01T18:00:00Z",0.8516823188825989,"9"],["1970-01-01T18:00:00Z",0.4822347226342143,"2"],["1970-01-01T18:00:00Z",0.8537704917434018,"e"],["1970-01-01T18:00:00Z",0.6474893614363054,"8"],["1970-01-01T18:00:00Z",0.12084258020287875,"b"],["1970-01-01T18:00:00Z",0.10028922464152086,"5"],["1970-01-01T18:00:00Z",0.10714141906342861,"d"],["1970-01-01T18:00:00Z",0.5602394543211429,"4"],["1970-01-01T18:00:00Z",0.6136735721749687,"6"],["1970-01-01T18:00:00Z",0.6423870400644192,"7"],["1970-01-01T18:00:00Z",0.015308939142130178,"a"],["1970-01-01T18:00:00Z",0.7245567220391249,"1"],["1970-01-01T18:00:00Z",0.35668866215579986,"0"],["1970-01-01T18:00:00Z",0.964093877408596,"3"],["1970-01-01T18:00:00Z",0.4502258725814664,"c"],["1970-01-01T19:00:00Z",0.8926780027343512,"3"],["1970-01-01T19:00:00Z",0.34511375974652964,"c"],["1970-01-01T19:00:00Z",0.3695828033675775,"a"],["1970-01-01T19:00:00Z",0.23677732966456128,"6"],["1970-01-01T19:00:00Z",0.7530421062432995,"4"],["1970-01-01T19:00:00Z",0.24086271163719555,"b"],["1970-01-01T19:00:00Z",0.43928988242351025,"8"],["1970-01-01T19:00:00Z",0.9768159766224415,"2"],["1970-01-01T19:00:00Z",0.8089394326442979,"9"],["1970-01-01T19:00:00Z",0.1972163932601322,"1"],["1970-01-01T19:00:00Z",0.905790296254551,"7"],["1970-01-01T19:00:00Z",0.36110701611589413,"5"],["1970-01-01T19:00:00Z",0.8306216297397975,"e"],["1970-01-01T19:00:00Z",0.01815565308147712,"0"],["1970-01-01T19:00:00Z",0.1606668523214809,"d"]]}]}]}

And given the following query:

    SELECT sum(f) FROM m WHERE time >= 0 AND time <= 20h GROUP BY t

After running through the transpiler the result is:

    {"results":[{"statement_id":0,"series":[{"name":"m","columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",140.5557660344789]]}]}]}

InfluxQL produces:

    {"results":[{"statement_id":0,"series":[{"name":"m","tags":{"t":"0"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",6.401565996565146]]},{"name":"m","tags":{"t":"1"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",10.41370192333676]]},{"name":"m","tags":{"t":"2"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",10.287277490313016]]},{"name":"m","tags":{"t":"3"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",9.980294311404334]]},{"name":"m","tags":{"t":"4"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",9.260426040799974]]},{"name":"m","tags":{"t":"5"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",8.951377254390621]]},{"name":"m","tags":{"t":"6"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",8.594402170720397]]},{"name":"m","tags":{"t":"7"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",10.324692765646258]]},{"name":"m","tags":{"t":"8"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",9.819678578070553]]},{"name":"m","tags":{"t":"9"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",10.14579475067564]]},{"name":"m","tags":{"t":"a"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",11.138582664234008]]},{"name":"m","tags":{"t":"b"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",6.808500678785872]]},{"name":"m","tags":{"t":"c"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",9.212761052323888]]},{"name":"m","tags":{"t":"d"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",7.735170142889512]]},{"name":"m","tags":{"t":"e"},"columns":["time","sum"],"values":[["1970-01-01T00:00:00Z",11.481540214323001]]}]}]}

InfluxQL gives a result with multiple data points, each having the zero time, whereas the transpiler gives a result with a single data point, also with the zero time.

**Comment by jsternberg** [comment]
Your input data looks incorrect. The `fromInfluxqlJSON` treats the `t` as a field rather than a tag because  it is in the columns section.

**Comment by jlapacik** [comment]
I am closing this issue due to invalid input data. #1337 has been updated with the correct input data and all tests pass.
