### ISSUE TITLE
GET /api/v2/tasks/TASKID should return task flat, with embedded links. 

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/platform#1391]
currently the GET `/api/v2/tasks/TASKID` endpoint returns:
```{ "links":{..."}, "task":{ "id":"...", "organizationId":"...", "name":"..." ...}```

should return:
```{"id":"...", "organizationId":"...", "name":"..." ..., "links":{...}}```

**Comment by mark-rushakoff** [comment]
The swagger for the Task object schema also needs to mention the links.

**Comment by mark-rushakoff** [comment]
This is done now.
