### ISSUE TITLE
GET /api/v2/tasks?user=USERID should return links embedded in each task

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/platform#1392]
currently the GET `/api/v2/tasks?user=USERID` endpoint returns:
```{ "links":{...}, "tasks":[{ "id":"...",  ...},{ "id":"...",  ...},{ "id":"...", ...}]```

should return:
```{ "links":{...}, "tasks":[{ "id":"...",  ..., "links":{...}},{ "id":"...",  ..., "links":{...}},{ "id":"...", ... , "links":{...}}]```

**Comment by mark-rushakoff** [comment]
Swagger for listing task response probably needs to be updated as part of this, too.

**Comment by mark-rushakoff** [comment]
This is done now.
