### ISSUE TITLE
Unable to build after installing influxdb

### ISSUE THREAD

**Issue by kslk10** [influxdata/platform#1395]
D:\Go\projects\src\github.com\influxdata\influxdb>go get -u -f ./...
# github.com/influxdata/influxdb/flux/functions/inputs
flux\functions\inputs\buckets.go:40:44: cannot use bd.alloc (type *execute.Alloc
ator) as type *memory.Allocator in argument to execute.NewColListTableBuilder
flux\functions\inputs\buckets.go:90:36: cannot use a.Allocator() (type *memory.A
llocator) as type *execute.Allocator in field value
# github.com/influxdata/influxdb/services/httpd
services\httpd\handler.go:1194:11: results.Cancel undefined (type flux.ResultIte
rator has no field or method Cancel)

D:\Go\projects\src\github.com\influxdata\influxdb>go build ./...
# github.com/influxdata/influxdb/flux/functions/inputs
flux\functions\inputs\buckets.go:40:44: cannot use bd.alloc (type *execute.Alloc
ator) as type *memory.Allocator in argument to execute.NewColListTableBuilder
flux\functions\inputs\buckets.go:90:36: cannot use a.Allocator() (type *memory.A
llocator) as type *execute.Allocator in field value
# github.com/influxdata/influxdb/services/httpd
services\httpd\handler.go:1194:11: results.Cancel undefined (type flux.ResultIte
rator has no field or method Cancel)

**Comment by goller** [comment]
Hi @kslk10, thanks for writing in!

It looks like you were trying to build `influxdb` on windows.
Do you mind adding this issue in that repository? 
It is here: https://github.com/influxdata/influxdb/issues/new?labels=&template=bug-report.md

**Comment by mark-rushakoff** [comment]
@kslk10 I don't think `go get` is expected to work that way. Use `dep ensure` per the contributing directions: https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#build-and-test

**Comment by kslk10** [comment]
Thanks for the reply. using dep ensure, the build was successful.
