### ISSUE TITLE
Should be able to query self source

### ISSUE THREAD

**Issue by chnn** [influxdata/platform#1425]
Currently, a `POST /api/v2/sources/<self_source_id>/query` with an appropriate JSON body will return the error
```
self source type not implemented
```
which originates here:

https://github.com/influxdata/platform/blob/23b94ac1f6ef827fd3db5585f8caa0a468535463/source/query.go#L13-L19

**Comment by goller** [comment]
@fntlnz @desa I was thinking that the /api/v2/sources/self_source_id would return links back to / rather than also contain all the endpoints.

What do y'all think?

**Comment by desa** [comment]
I think I could get into that idea. As an aside, I'd like to get rid of the idea of a self source. I wonder if it would be worth rethinking the idea of sources/remotes.

**Comment by goller** [comment]
@desa I do like the idea of just remotes... @chnn remind me how you wanted to handle this?
