### ISSUE TITLE
/v1/bucket endpoint should support different time durations for retentionPeriod 

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#144]
v1/bucket endpoint for creating the buckets currently only accepts pure integers, i.e. 3, 4, etc, which defaults to `ns`. It should be able to handle other time durations as well, such as seconds, minutes, hours, weeks.

**Comment by goller** [comment]
Duplicate of #796

**Comment by gshif** [comment]
https://github.com/influxdata/platform/pull/864
