### ISSUE TITLE
Add twinkling loading animation to the upload line protocol card

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#1483]
as a new user
with admin permissions or higher
when i am loading a line protocol file
then i would like to see a twinkling loading animation an an indicator of progress.

**Comment by mavarius** [comment]
![sparkle](https://user-images.githubusercontent.com/11937365/49103933-872d1c80-f231-11e8-8a8e-061323b39e8e.gif)

**Comment by ebb-tide** [comment]
blocked on https://github.com/influxdata/platform/issues/1476
