### ISSUE TITLE
Add the ability to manually run a task independent of its scheduled run

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#1490]
as a task user
with admin permissions or higher
when i create a task
then i would like the ability to manually execute that task

the task could be scheduled or unscheduled
run records and logs should be stored just like a normal task

**Comment by mark-rushakoff** [comment]
Is this a new type of task that has no schedule? Or is this forcing a run of a task, that has a Cron or Every schedule? Is it okay if the time for the run does not match the schedule - meaning, if the task is configured to run every hour, can I make it run at 5m22s past the hour, or does the run have to match the schedule and be exactly on the hour?

**Comment by russorat** [comment]
Is this a new type of task that has no schedule? Or is this forcing a run of a task, that has a Cron or Every schedule? 
 - this is forcing it to run outside of its schedule, not a new type of task

Is it okay if the time for the run does not match the schedule - meaning, if the task is configured to run every hour, can I make it run at 5m22s past the hour
 - yes, using this manual option you could run it outside of the hour. We should have some indication in the run record that this was a manual run, and not executed by the scheduler. Ideally, the user that kicked it off.

**Comment by mark-rushakoff** [comment]
Need to decide detail for swagger on this. Sounds otherwise straightforward.
