### ISSUE TITLE
should be able to view a single stat

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#1526]
as a query builder
with admin permissions or higher
when i build a dashboard cell
then i would like the ability to visualize that data as a single stat graph
then i would like the ability to display a trend line behind the single stat
then i would like the ability to display text or numbers
then i would like the ability to set a prefix or postfix for the value
then i would like the ability to set the precision of a single stat
then i would like the ability to set any number of thresholds for this single state
then i would like the ability to change the color of the text or the background of the single stat
then the size of the single stat should change relative to the size of the graph cell

**Comment by chnn** [comment]
Blocked on #1570 (this will share some of the same implementation)
