### ISSUE TITLE
Consider Renaming the task option field `every` to `interval`

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/platform#1574]
The name: `task.every` doesn't suggest anything to a naive user about what the field is referring to. 
The name `task.interval` on the other hand, suggests that the task will be running at the specified interval. Interval is also a noun, so you can use it in a sentence like `what is the interval of this task?` whereas `what is the every of this task` does not make similar sense. 

We are renaming the option field in the tasks UI to interval so that the user can understand what the field refers to, and this is causing a mismatch between the UI reference to the field and the flux script reference to it. 

<img width="485" alt="screen shot 2018-11-26 at 2 46 59 pm" src="https://user-images.githubusercontent.com/10937678/49047213-9194db00-f18b-11e8-8bb0-2c056d79b99e.png">

**Comment by mark-rushakoff** [comment]
@russorat said we won't do this.
