### ISSUE TITLE
GET to /api/v2/telegrafs/{telegrafID} does not fuzzy match on Accept header

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/platform#1587]
A GET request to '/telegrafs/{telegrafID}' with header `{"Accept" : "application/json, text/plain, */*"}` should return what is specified as expected from a request with header `{"Accept: "application/json"}`
 as defined in: https://github.com/influxdata/platform/blob/e2959c61b7824185d16858b815c0b725497d6225/http/swagger.yml#L148

This is because https://github.com/influxdata/platform/blob/e2959c61b7824185d16858b815c0b725497d6225/http/telegraf.go#L155 is performing an exact match on the Accept header. 

Also: This issue was obscured because the default behavior of the API is not specified in the Swagger spec, even though the API does have a default behavior. It would be really nice to have default behavior described, when it exists.

**Comment by goller** [comment]
I have a basic branch, but, I found several bugs in the API.  This lead me to writing the swagger test framework.

I'll circle back to this once the swagger tests are complete
