### ISSUE TITLE
Creating org name with a back-slash using REST API returns an error

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#163]
I have try creating a org name with a back-slash using influx cli tool, and tried just with a rest api.
When I pass a name like `hello\` or `hello\\` or `hello\\\`, I am getting `Unexpected EOF`
>a=requests.post('http://localhost:9999/v1/orgs',data='{"name":"hello2\\"}')
a.status_code -->500
a.headers --> {'Date': 'Thu, 21 Jun 2018 21:22:46 GMT', 'X-Influx-Error': 'unexpected EOF', 'Content-Length': '0', 'X-Influx-Reference': '1'}

>a=requests.post('http://localhost:9999/v1/orgs',data='{"name":"hello2\\\"}')
a.headers -->{'Date': 'Thu, 21 Jun 2018 21:23:01 GMT', 'X-Influx-Error': 'unexpected EOF', 'Content-Length': '0', 'X-Influx-Reference': '1'}

When I pass `hello\\\\` (with a four back-slashes), the name is created, but with double back-slash, e.g.
>a=requests.post('http://localhost:9999/v1/orgs',data='{"name":"hello2\\\\"}')
a.headers --> {'Date': 'Thu, 21 Jun 2018 21:23:09 GMT', 'Content-Length': '44', 'Content-Type': 'application/json; charset=utf-8'}
a.json() -->{u'id': u'02350e0aca6de000', u'name': u'hello2\\'}

On the other hand, when I am using an `influx` tool, it works:
`influx org create -n "hello3\\"`
>ID			                 Name
02350f7b74ede000	hello3\

**Comment by goller** [comment]
@gshif this is correct behavior.

when in python the \\ evaluates to the literal \ (python escapes first).  
Next, the json is evaluated and the server determines that the json has a single extra JSON.

When \\\\ : 
python evals to \\ and json evals to an escaped \
