### ISSUE TITLE
Publish a nightly build to Quay for Flux

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/platform#167]
Having a nightly tagged as nightly  -- like Chronograf see below -- for Flux will allow us to integrate this into a "nightly" sandbox.  Essentially, we want to provide an option for folks to use either a stable build or a nightly build of our bits through a standard set of docker containers.

<img width="1416" alt="screen shot 2018-06-22 at 9 06 41 am" src="https://user-images.githubusercontent.com/23535264/41787565-a5465962-75fd-11e8-9db2-3c7287584a98.png">

**Comment by jsternberg** [comment]
@nathanielc I don't see anything in `goreleaser` about docker so I think this image build will be similar to the influxdb nightly. I'll find where `goreleaser` runs though and try to get the docker build to happen in the same place or at least be triggered by the nightly build if I can.

**Comment by jsternberg** [comment]
@nathanielc what should the image name for this be?

**Comment by jsternberg** [comment]
goreleaser/goreleaser#727
