### ISSUE TITLE
rest api: deleting organization returns status 202

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#170]
Since there is no swagger documentation for deleting the organization I have followed the syntax of `influx` tool, e.g.
`requests.delete('http://localhost:9999/v1/orgs/<org_id>`
The following issues exist:
- If org_id exists, then request status is 202. (I am assuming it not supposed to return a json response)
- if org_id does not exist, then request status is 500, and error message is part of a header.

**Comment by jademcgough** [comment]
Can you clarify what's incorrect or unexpected here?

A 500 seems reasonable for an invalid URL, and a 202 seems fine for a deletion response (though it's invalid with our use of 204's elsewhere).

**Comment by gshif** [comment]
- I was looking at our existing rest api documentation and for every successful delete request HTTP response is always 204, which, according to the wiki, `The server successfully processed the request, but is not returning any content.`. As for the response 202 - `The request has been accepted for processing, but the processing has not been completed. The request might or might not eventually be acted upon, as it might be disallowed when processing actually takes place`. In my humble opinion, I think we should be sticking with 204.
- I would disagree with returning the HTTP response 500 as a default error code as it is a generic message given when no more specific message(s) is suitable. In our current rest api doc, we return a specific error/message first (in this case for unknown org_id), that being 404 and then , for every other error - unexpected server error.

Hope my explanation helps.
