### ISSUE TITLE
Error response is missing 'err' key

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#1830]
Creating a duplicate org will return an error message, but it is missing one of the keys - `err` (http://docs.internal/api/swagger/#tag/Organizations/paths/~1orgs/get):
- Testing against latest nightly influx build.
- Create an org that already exists:
```
r = requests.post('http://localhost:9999/api/v2/orgs', data='{"name":"org_name"}', headers={'Authorization':'Token 40cqDWMbzMSlXToDlgEf3dNosxgonzakYAQ-3QtdVH3UNw6-qR475FXkuCILEin8qvHpYLwHp9x9wknEOVMreg=='})
```

- Get a json response object:
```
r.json()
{u'msg': u'organization with name org_name already exists', 
 u'code': u'conflict', 
 u'op': u'bolt/CreateOrganization'}
```

The error response schema has three key/value pairs:
- msg
- code
- op

The `err` key is missing.

**Comment by jademcgough** [comment]
I've updated the swagger for this - only code and message should be considered required in error responses.
