### ISSUE TITLE
Support table configuration in table component

### ISSUE THREAD

**Issue by chnn** [influxdata/platform#1849]
The [`TimeMachineTables` component](https://github.com/influxdata/platform/blob/bafeadf57d124d0c3fe09ac408390b47318ff408/ui/src/shared/components/tables/TimeMachineTables.tsx) should support all the configuration in it's underlying view type:
```
type TableViewProperties struct {
	Type              string           `json:"type"`
	Queries           []DashboardQuery `json:"queries"`
	ViewColors        []ViewColor      `json:"colors"`
	TableOptions      TableOptions     `json:"tableOptions"`
	FieldOptions      []RenamableField `json:"fieldOptions"`
	TimeFormat        string           `json:"timeFormat"`
	DecimalPlaces     DecimalPlaces    `json:"decimalPlaces"`
	Note              string           `json:"note"`
	ShowNoteWhenEmpty bool             `json:"showNoteWhenEmpty"`
}
```
Note that this is a separate story from #1819, which adds the UI for editing these configuration options.

**Comment by ebb-tide** [comment]
Some of these are closed by https://github.com/influxdata/platform/pull/2092 but we should go over all requirements again.
