### ISSUE TITLE
document ready endpoint in swagger

### ISSUE THREAD

**Issue by goller** [influxdata/platform#1906]

**Comment by lyondhill** [comment]
Ready is used in enterprise. It was added here in #1581. I can move it to enterprise or document it in platform @goller which would you prefer? Sorry I missed the documentation on the first pass.

**Comment by goller** [comment]
@lyondhill I it should be moved to enterprise.  That way we would have only one way to communicate health using the /health endpoint.

**Comment by lyondhill** [comment]
sounds good. I will move it.
