### ISSUE TITLE
Move IFQL issues to platform

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/platform#197]
Iterate the influxdb issues that are labelled `ifql triaged` and
  - Follow the link to the ifql repo.
  - Move the ifql issue to the platform issue (there’s a chrome extension to help with this)
  - Write a flux test case for the feature; Add it to the skip list of not yet working
  - Keep a list of these in a google sheet — note which work, which fail, and what the platform issue no. is.

**Comment by mark-rushakoff** [comment]
Can this issue be closed now? @aanthony1243 @adamperlin

**Comment by adamperlin** [comment]
@mark-rushakoff yes
