### ISSUE TITLE
owner/member endpoints are timing out

### ISSUE THREAD

**Issue by jademcgough** [influxdata/platform#1987]
Introduced by https://github.com/influxdata/platform/pull/1486:

`UserService` is being used in the `NewTaskHandler` method for `BucketService`, `DashboardService`, `OrganizationService` and `TaskService` before it's been assigned.

**Comment by zhulongcheng** [comment]
Hi @jademcgough, I will fix this bug today. Sorry, i caused this bug.

TODO:
[ ] Pass `UserService` to `New[resource]Handler`
[ ] Add mocked UserService, and use it in `http/[resource]_test.go`
