### ISSUE TITLE
Benchmark Platform read and write performance

### ISSUE THREAD

**Issue by e-dard** [influxdata/platform#1995]
We should carry our high level tests to benchmark the read and write performance of the Platform read/write path.

As a minimum we should replicate the set of write and query workloads we carry out as part of our internal nightly performance harness.

I expect that the write performance should be almost identical to 1.7, but the read performance could vary considerably depending on the type of query.

**Comment by benbjohnson** [comment]
Initial performance metrics have been measured. Closing and moving on to https://github.com/influxdata/platform/issues/2148 for further discussion.
