### ISSUE TITLE
Check if the organization exists during bucket creation

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#2072]
GET request for `api/v2/buckets` endpoint with/out parameters returns status code 404 and error:
`organization not found`.
Run `curl -GET http://localhost:9999/api/v2/buckets -H "Authorization:Token <token>"` command:
It'll return:
```
{"code":"not found","msg":"organization not found","err":{"code":"","err":{"code":"not found","msg":"organization not found"}}}
```

The same error would be return if you use `org` and `orgID` parameters.
I am using the nightly build. 
https://github.com/influxdata/platform/blob/master/http/swagger.yml#L2473-L2508

**Comment by goller** [comment]
I dug into this issue @gshif.

The create bucket code does not check if the organization actually exists.

https://github.com/influxdata/platform/blob/master/bolt/bucket.go#L305
https://github.com/influxdata/platform/blob/master/inmem/bucket_service.go#L205

**Comment by goller** [comment]
```go
		if !b.OrganizationID.Valid() {
			o, err := c.findOrganizationByName(ctx, tx, b.Organization)
			if err != nil {
				return err
			}
			b.OrganizationID = o.ID
		}
```

This is also a possible authorization escalation. If one puts 0 as the orgID and a different org name as compared to the authorization, then one can create buckets in a different organization.

These types of data normalization checks should happen in the HTTP REST code and not the storage layer.

**Comment by gshif** [comment]
@goller , According to the swagger doc you can only create a bucket when `org` is specified as a parameter. My original tests are not using `org` as a parameter. Should the error be returned in this case?
For example, this request does not return the error, but successfully creates a bucket
```
requests.post('http://localhost:9999/api/v2/buckets', data='{"name":"my_bucket","organizationID":"031e6677492dc000", "retentionRules":[{"type":"expire","everySeconds":1182}]}', headers={'Authorization':'Token %s' % token})
b.status_code
```
