### ISSUE TITLE
SPEC: add syntax for array and object literals

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#212]
From ifql created by [jsternberg](https://github.com/jsternberg) : influxdata/ifql#347  

There is no specification for what an array literal is and what an object literal is. I think this is also needed because object literals and blocks are opened using the same symbol so we need to differentiate how the two are different in the language syntax.

**Comment by nathanielc** [comment]
Adding some details here:

Arrays are enclosed in `[]` and delimited with commas.

Objects are enclosed in `{}` and delimited with commas. 

Trailing commas are valid for both.

The object syntax has three variants:

Basic object literal
```
{
    foo: "bar",
    jim: "bob",
   every: 10s,
}
```

Implicit keys literal
```
{ sum, mean, count }
// the above is equivalent to 
{ sum: sum, mean: mean, count: count }
```

Keys as an expression:
```
var k = "mykey"

{ [k]: "value" }
// the above evaluates to this literal
{ "mykey": "value" }
```

**Comment by nathanielc** [comment]
@pauldix Also suggested that we could diverge from the JS syntax and use string interpolation for key expressions. 

```
k = "mykey"
{ "{k}": "value"}
```

**Comment by jlapacik** [comment]
This requires error handling to be implemented in the parser. I'm placing this back on the backlog and will pick back up when https://github.com/influxdata/flux/issues/305 is added.
