### ISSUE TITLE
cannot build with nonexistent file `github.com/influxdata/platform/chronograf/.eslintrc`

### ISSUE THREAD

**Issue by KielChan** [influxdata/platform#2143]
`github.com/influxdata/platform/chronograf/.eslintrc` refers to nowhere cos` no ui dir!
anybody can fix it?

**Comment by mark-rushakoff** [comment]
I see - `./chronograf/.eslintrc` is a symlink to a file that does not exist.

It looks like 6eb21d3dded92342ed9279f4a6959400447a4457 removed the content of .eslintrc back in October.

Is the fix just to remove `chronograf/.eslintrc`? cc @121watts

**Comment by 121watts** [comment]
@mark-rushakoff that should do it.

**Comment by KielChan** [comment]
After removing the file, `go build` cmd can  make it a success
