### ISSUE TITLE
service: add inmem/mock implementation of services

### ISSUE THREAD

**Issue by zhulongcheng** [influxdata/platform#2145]
services:
- [x] SourceService
- [x] OnboardingService
- [x] ProxyQueryService
- [x] PointsWriter
- [x] DashboardOperationLogService
- [x] BucketOperationLogService
- [x] UserOperationLogService
- [x] OrganizationOperationLogService
- [x] TelegrafService
- [x] ScraperTargetStoreService

**Comment by goller** [comment]
TelegrafService added in #2138

**Comment by leodido** [comment]
:100:
