### ISSUE TITLE
Cannot delete last dashboard

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#2183]
trying to delete the last dashboard and i cannot. it returns after a refresh.

![kapture 2019-01-02 at 12 33 19](https://user-images.githubusercontent.com/4805997/50611313-bf57f880-0e8a-11e9-80b3-b97b2e2a0c12.gif)

**Comment by ebb-tide** [comment]
Should be fixed by https://github.com/influxdata/platform/pull/2250
