### ISSUE TITLE
A DELETE on dashboards should not error if a view in the dashboard can not be found. 

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/platform#2191]
deleting a dashboard with a view that is somehow corrupted or not available causes the delete operation on the dashboard to error, and creates zombie dashboards that can not be removed. 
A DELETE request which errors in this way also returns a strange, nested error:

```code: "not found"
error: {code: "", error: {code: "not found", message: "view not found"}}
message: "view not found"
op: "bolt/DeleteDashboard"
```

**Comment by desa** [comment]
@ebb-tide can you include the steps to reproduce this issue.

**Comment by ebb-tide** [comment]
should be fixed by: 
https://github.com/influxdata/platform/pull/2250
