### ISSUE TITLE
Add the ability to display the token in the UI

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#2285]
as a new user
with admin permissions or higher
when i view the list of tokens
then i would like the ability to view the text of the token
then i would like the ability to copy the text of the token to my clipboard

**Comment by russorat** [comment]
let's use the show code component

**Comment by bthesorceror** [comment]
Use the same method we use to show tokens in onboarding.

**Comment by ischolten** [comment]
can be found in the component TelegrafInstructions.tsx
