### ISSUE TITLE
EOF error when trying to write points via CLI

### ISSUE THREAD

**Issue by kevinhogan111** [influxdata/platform#2318]
STR:

1) I installed the nightly build from here: https://s3.amazonaws.com/dl.influxdata.com/platform/nightlies/influx_nightly_darwin_amd64.tar.gz
2) I have the following creds:

You have entered:
  Username:          khogan
  Organization:      kevin_test_org
  Bucket:            kevin_test_bucket
  Retention Period:  168 hrs
Confirm? (y/n): y

UserID			      Username	Organization	     Bucket			        Token
03369df407344000   khogan	kevin_test_org	kevin_test_bucket	      <my token 

3) I'm getting EOF errors when I try to write line protocol to my bucket/org via:

./influx write /Users/kevin/Downloads/influx_nightly_darwin_amd64/NOAA_data.txt -b kevin_test_bucket -o kevin_test_org --token <my_token>

```
Error: EOF
Usage:
  influx write line protocol or @/path/to/points.txt [flags]

Flags:
  -b, --bucket string      name of destination bucket
      --bucket-id string   ID of destination bucket
  -h, --help               help for write
  -o, --org string         name of the organization that owns the bucket
      --org-id string      id of the organization that owns the bucket
  -p, --precision string   precision of the timestamps of the lines (default "ns")

Global Flags:
      --host string    HTTP address of Influx (default "http://localhost:9999")
      --local          Run commands locally against the filesystem
  -t, --token string   API token to be used throughout client calls

EOF

```
I get the same EOF error when I try the commands with quotes:

   ./influx write /Users/kevin/Downloads/influx_nightly_darwin_amd64/NOAA_data.txt -b "kevin_test_bucket" -o "kevin_test_org" --token "<my_token>"
  
 ./influx write /Users/kevin/Downloads/influx_nightly_darwin_amd64/NOAA_data.txt -b 'kevin_test_bucket' -o 'kevin_test_org' --token '<my_token'>

Opened an issue as I'm not sure if this is a real issue or user error.

**Comment by gshif** [comment]
@goller , looks like you worked on it. Would you take a look. Thanks

**Comment by desa** [comment]
@kevinhogan111 is there an associated server panic?

**Comment by gshif** [comment]
@desa , @kevinhogan111 , looks like we were using the nightly build that is 7 days old. After building the latest platform@master the `influx write ...` is not failing:
- ./influx write -b "a" -o "a" -t "-pWn5fCwomE9q0oTBHtHN7xmRhQwzfLZ6tmvEAhhn9-Lz5Zf-6qB1GrgLtedMa614kgs8Q96rxhNZCAEt_drcA==" "cpu,r=1 f=1"
- The exit status of the command is 0, alse WAL file has the point

**Comment by gshif** [comment]
It is also working with files. If `@` is omitted in the beginning of the path to a file, then we would get the above error, otherwise it is ok:
- File: cpu,t=1 f=1
- ./influx write -b "a" -o "a" -t "-pWn5fCwomE9q0oTBHtHN7xmRhQwzfLZ6tmvEAhhn9-Lz5Zf-6qB1GrgLtedMa614kgs8Q96rxhNZCAEt_drcA==" @../../../idpe/litmus/text.txt
- No errors and exit code is 0, also data is in the WAL file
