### ISSUE TITLE
update-golang submodule

### ISSUE THREAD

**Issue by AdamJacobMuller** [influxdata/platform#2355]
https://github.com/influxdata/platform/commit/44feb51386fb24637455954094babe7542e6bad9 this commit appears to have (inadvertently i assume) added a gitlink submodule with no corresponding .gitmodules. I assume it was added in error?

**Comment by mark-rushakoff** [comment]
Correct, the submodule was somehow added by mistake, and it was missed in review. #2357 removes the submodule. Thanks for bringing it to our attention.

**Comment by AdamJacobMuller** [comment]
thanks mark!
