### ISSUE TITLE
Flakey Test

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#236]
From ifql created by [docmerlin](https://github.com/docmerlin) : influxdata/ifql#371  

There is some flakeyness either in the tests or the testing framework.

compare 
https://circleci.com/gh/influxdata/ifql/606
and 
https://circleci.com/gh/influxdata/ifql/607

**Comment by aanthony1243** [comment]
this is 2 months old.  Will reopen if test fail again.
