### ISSUE TITLE
Add options to query language for Tasks

### ISSUE THREAD

**Issue by pauldix** [influxdata/platform#24]
The tasks API will need a three separate concepts represented: how frequently to run the task, a cron style schedule (more flexible version of frequency), and the representation of what `now` means for the IFQL script as it is executing. There are three things I'd like to discuss and address in this issue:

1.  Where should this information be kept? In the IFQL script or as task API metadata?
1.  How should we set the execution context of `now` time in IFQL? In the script? Part of API?
1.  What should these concepts be named?

I'll lay out an example to illustrate the different issues. Say you have the following query that you want run periodically:

```javascript
from(bucket:"foo")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> min()
  |> to(bucket:"bar")
```

So you're calculating the min value every one hour and outputting those results to the `bar` bucket. If the tasks scheduler simply kicked off this query every hour, we'd need to set the `now` time within that context so that the relative range is correct. Really, we'd want `now` to return whatever `now()` was at the start of the query, rounded to the nearest hour.

Another thing we want to expose to the user is the idea of having something run periodically, but to have it wait for a little bit before executing. For example, with our query above if we wanted it to wait until five minutes past the hour to run, but to act as though it is being run on the hour exactly, to facilitate some window of time for late data arrival. This could be `every_offset` or something like that.

In our initial iteration of tasks we should do the simple case for handling late arriving data, which is to just wait. For historical backfills or to fix something when they go over that window of time, we should have an API that allows the user to request a recalculation of the task for the historical window.

For example, if I fill data from yesterday, I want to tell the API to run the above script for every hour of yesterday (even while it is still going to run for the next hour of today when it rolls over).

Here are three different options I can think of to represent this:

## Option 1 - in IFQL

This data could be options at the top of the IFQL script. Here's a swag at it:

```
period = 1h
option every = period
option every offset = 5m
// option cron = "..." // this and every options would be mutually exclusive

// this changes the behavior of now() in the rest of the script to return the 
// time. round(...) could also be a date time literal. This also changes any
// relative time arguments to functions in IFQL
option now = round(time:now(), 1h)

from(bucket:"foo")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> min()
  |> to(bucket:"bar")
```

## Option 2 - Tasks API & now as query request argument

This option would have the Tasks API keep the metadata for every, offset, and cron. The IFQL query process would need to accept an argument that sets the `now` execution context of the script.

## Option 3 - Tasks API & option now in IFQL

This option would only move the setting of `now` into the IFQL script while all other data is kept by the Tasks API.

Thoughts from @goller @mark-rushakoff @jademcgough @nathanielc @docmerlin?

**Comment by desa** [comment]
One of the things that came up in Kapacitor was the desire to have [tasks loaded from a directory](https://github.com/influxdata/kapacitor/issues/1313). The challenge there was that TICKscript wasn't sufficient to describe a task. As a result, we ended up modifying TICKscript to include setting a dbrp. If IFQL cannot sufficiently describe all of the options required for a task, then we'll have to have some other file format to load tasks from a directory (provided that this is functionality that is desirable, which I think that it is).

I'd be strongly in favor of Option 1.

**Comment by docmerlin** [comment]
I like the idea of it being part of the IFQL options... but if it is, it also makes sense for it to be.  However if it is, the full CRUD actions should be doable from IFQL.

**Comment by pauldix** [comment]
@desa then another item that is missing in this is the `name` of the task. This will be important in the UI to distinguish it. We could also add `description`. Since that's more stuff and this is related to the idea of tasks directly, maybe this format would be better:

```
period = 1h
option task = {
    name: "paul's rad task",
    every: period,
    offset: 5m,
    // cron: "..."
}
option now = round(time:now(), duration:1h)

from(bucket:"foo")
  |> range(start: -period)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> min()
  |> to(bucket:"bar")
```

**Comment by pauldix** [comment]
@docmerlin I think I prefer the CRUD of tasks to be a separate API from one that just takes generic IFQL. Mainly for API cleanliness since running a query will be exposed via HTTP GET. That means that the query API would have to validate that there are no `output` function calls and would ignore certain options like `option task`. Similarly, the tasks CRUD API would validate that there is at least one `output` call and that the proper parameters are set on `option task` (or that those options are passed into the API, which will then rewrite the IFQL script with the relevant option.

**Comment by docmerlin** [comment]
Then you just want it to indepotently put in a task and possibly overwrite a task with the same name?

**Comment by nathanielc** [comment]
On question 1.

I think we should have all the information within IFQL the script. We started discussing this idea here: 
https://github.com/influxdata/ifql/issues/305

Having it all in the script allows for the information to be self contained. Kapacitor initially split metadata about a task from the script. Now all metadata for a task can be defined within the task itself. In short people wanted it to all exist in a single location.

That said it might be a good idea to support editing that data directly via the API without having to submit  a new script. This should be possible as IFQL is being designed to be easy to programatically manipulate.

On question 2

The query execution engine already supports `now` being an explicitly defined value. See https://github.com/influxdata/platform/blob/master/query/plan/physical.go#L18

This is not exposed via the query Spec but it should be with a default to time.Now(). 

On the question of old/late data

We already have a mechanism for that https://github.com/influxdata/platform/blob/master/query/docs/SPEC.md#triggers, but it is not exposed to users. The idea is that by using triggers an end user gets control over when data needs to be recomputed by defining the conditions given some simple events. This allows the user to express all the above use cases.

For example run query 5m after the hour for the previous hour is trigger when: `watermark > _stop + 5m`. For allowing recalculation of data that is late by a whole day you would use finish when: `watermark > _stop + 1d`. The combination of these becomes, after 5m compute the result, then if any arrives between 5m late and 1 day late recompute the result. So you only recompute the result for the case where data was more than 5m late. With this a user has a result quickly (after the first 5m) and a complete result that includes the entire day of late data. By moving these two boundaries around the user has control over the latency of their results, the completeness of their results and the cost to compute the results.

**Comment by nathanielc** [comment]
I almost forgot:

Triggers kind of imply that a query is long running waiting for the trigger events. But maybe we move the trigger logic into the task tier and simply submit new queries as needed based on the triggering logic.

I haven't really thought this through all the way. Only that I really like the flexibility that triggers have while  also being quite simple in concept.

**Comment by jademcgough** [comment]
> Then you just want it to indepotently put in a task and possibly overwrite a task with the same name?

The name would be used as a means of describing the task to users, not as a unique identifier. Each task would have its own unique ID, which would be generated on task creation. We can't make names unique, because tasks between different organizations could conflict.

**Comment by goller** [comment]
I'm also in favor of option 1.  however, I'd like some REST API niceties where the API exposes some/all of the option fields via `GET`; I'd allow those fields to be able to be `PATCH`ed.  However, the `GET`/`PATCH` would just be API beauty around ifql manipulation.

**Comment by mark-rushakoff** [comment]
I also favor the style of Option 1. There was some previous discussion around syntax for options, suggested name "directives", in https://github.com/influxdata/ifql/issues/305. One unresolved point there was whether directives/options are fully portable across any IFQL engine or portable to previous versions. Maybe the `option` syntax in this issue is more flexible in that regard.

Some other not-yet-mentioned benefits of keeping **everything** in IFQL:

- IFQL becomes completely shareable. Copy a script from a blog post and paste it into your editor, and you're ready to run after only changing minor details like bucket names.
- Keeps pressure on us to have full programmatic access to IFQL, to accomplish simplified changes such as modifying the cron schedule only from a different web UI.
- Simplified storage: the platform only needs to look up IFQL, doesn't need to look up IFQL and then join with some other data store. May slightly simplify backups too.

**Comment by pauldix** [comment]
Ok, so we're all in agreement on option 1.

@jademcgough I'd scope task name uniqueness by user (owner). That way they can update tasks based on the name without knowing what the ID is. Helps since they won't have the ID in their IFQL script, which is what would be checked into source control.

@nathanielc, triggers doesn't cover this case because of what you mention about them assuming a long running query. These queries are just run on a schedule. As for having the scheduler trigger based on incoming data, we can look at that in the future, but I don't want to worry about it in the near term. That's a cache invalidation problem so all we gotta do now is come up with a new name for this language and we've got a real rodeo here ;)

For this initial functionality I want to keep the execution simple. Give the users a single control to be able to specify that the scheduler should execute the query on a delay/lag. Then also give them the ability via the tasks API to re-run a task for some previous window of time (if they do historical backfill or if they need to fix up the data after some larger system problem).

Finally, we should settle in on what the syntax looks like. There are a few things to consider here. First, some options will have validation. For example, a task will require a `name` and either an `every` or a `cron`. The second thing to consider is what it looks like when we make changes in future versions of the language. We shouldn't break IFQL scripts that work when we create a new version. This might be easier to reason about/guarantee with different approaches (I'm not sure, but it's something I want us to be thinking about). For now, there are two options under consideration:

## Syntax Option 1

Use `<option> <name> <map>` to specify these options. This would expand the language spec. For our tasks example this would look like:

```
option task {
    name:"foo",
    every:1h,
    // cron: "..."
}
option now {
    time: round(time:now(), round:1h)

    // time is the power feature to set explicitly. here's a shortcut, but only time or round can be set
    // round: 1h
}
```

A slight modification to this could be to use `<option> <name> = <map>`.

## Syntax Option 2

Use functions to specify this information. Would look like this:

```
option(
    kind: "task",
    config: {
        name: "foo",
        every: 1h})
option(
    kind: "now",
    config: {round: 1h})
```

Or option could be called `directive` as in @mark-rushakoff's original proposal.

## My Vote

I prefer Syntax Option 1. Mainly because these options set things on the execution engine. And the way we think of functions is that they have no side effects. So the syntax of option 1 keeps this as a thing separate and distinct from any kind of regular function.

I'm not sure that either option is better or worse for future compatibility or for situations where the query engine will ignore the options (like if task information is specified, but the query is being run interactively).

**Comment by desa** [comment]
>  then another item that is missing in this is the name of the task.

We used the file path as the name when we loaded it from a directory and required that all tasks be defined in a single place. That may not be desirable for platform though.

I think the big thing for me is that, IMO, tasks should be definable with a single file without any external data.

Might also be interesting to have something like environment variables that can be loaded into tasks as options.

**Comment by docmerlin** [comment]
```The name would be used as a means of describing the task to users, not as a unique identifier. Each task would have its own unique ID, which would be generated by the service on task creation. We can't make names unique, because tasks between different organizations could conflict.```

In terms of user-interface ergonomics, it might be nice to have some sort of per-organization uniqueness on names.

**Comment by pauldix** [comment]
@desa: The tasks system shouldn't have any host specific knowledge. That is, it shouldn't have files or environment variables or any of that. We'll have something so that people can load tasks from files, but that would be a feature of the CLI that reads a directory or file and makes calls to the API.

In 2.0, everything should be done via the API, including configuration. The only config that should be set would be something that is specific to a host (like max disk or memory to use, hostname, etc). We'll have config files, but the pattern will be to load them via the CLI. At least that's what I'm thinking for now.

**Comment by nathanielc** [comment]
Syntax option 1 has a nice advantage in that the parser can enforce that the options are at the beginning of the file. Like Go's `import` statements. I also like the point that we try and treat functions like they do not have side effects.

So the psuedo grammar for options would be something like:

```
OptionStatement = "option" Identifier ObjectExpression
```

As for triggers I agree we need to leave that till later. My point in bringing them up is that their use tends to expose three knobs and I'd like the simple knobs we expose to the user now to map well to how trigger will work later. The common trigger knobs are:

 * schedule - the schedule on which to run the queries,
 * lag - the lag or offset from the current time to treat as the `now` time for the query,
 * horizon - the offset duration after which we no longer care about recomputing results.

The `horizon` knob is the part that introduces cache invalidation, so for now if we expose only the `schedule` and `lag` time then we set ourselves up well for when triggers are expose directly. Setting `horizon = lag` essentially eliminates the cache invalidation problems, which is what IFQL is doing now.

**Comment by pauldix** [comment]
Ok, we've settle on this:

```javascript
option task {
  // name is required, and must be unique for a give user_id & organization_id
  name: "foo"
  // every is a duration, this task should be run at this interval. minimum interval is 1s.
  every: 1h
  // delay is a duration, in this example it would delay scheduling the task to
  // 10 minutes past the hour
  delay: 10m
  // cron is a more sophisticated way to schedule. every and cron are mutually exclusive
  cron: "0 2 * * *" // run at 2 AM
  // retry is the number of times to retry a failed run of a task before
  // giving up. This isn't in scope of initial implementation
  retry: 5
}
```

We'll use this issue to track the work. #37 adds the option for setting the execution time.

**Comment by nathanielc** [comment]
We may want to change the syntax slightly...

```
option task = {
  // name is required, and must be unique for a give user_id & organization_id
  name: "foo"
  // every is a duration, this task should be run at this interval. minimum interval is 1s.
  every: 1h
  // delay is a duration, in this example it would delay scheduling the task to
  // 10 minutes past the hour
  delay: 10m
  // cron is a more sophisticated way to schedule. every and cron are mutually exclusive
  cron: "0 2 * * *" // run at 2 AM
  // retry is the number of times to retry a failed run of a task before
  // giving up. This isn't in scope of initial implementation
  retry: 5
}

// Now in the rest of the script the values of task can be accessed.

from()
    |> range(start:-task.every)
   //...
```

So the grammar would be:

```
OptionStatement = "option" Identifier "=" Expression
```

This allows options to be any valid expression. Validation that the option is assigned the correct type will not be part of the grammar, but a function of the execution model.

**Comment by nathanielc** [comment]
Also quick question: We are calling these `options`, what is optional about these values? 

For example the `now` option is not optional in that all queries need a `now` time. But it is optional in that the now option has a default value so if its not present in the script, the default will be used.

In other words this mean all `options` must have default values or they are not optional. Do all of the current options have clear defaults? If not should we call these something else?

**Comment by pauldix** [comment]
We could change it to `set` or `use`. I think I prefer the former.

**Comment by nathanielc** [comment]
Both `set` and `use` are verbs and make it confusing what the difference is between

```
set task = {...}

// and

foo = { ... }
```

Clearly there is something special about how `task` is assigned but it is not clear what.
I think `use` is a little better in that case.

I prefer a noun for the keyword that describes what it is. Maybe directive? 

```
directive task = { ... }
```

Then a user can search `what is an ifql directive?` and land on the right docs.

And to be clear I am fine with `option` so long as these are really option values.

**Comment by pauldix** [comment]
Well, they do seem optional, no? The now option is set by default and the others can all be zeroed by default. One thing to note is that if the user is submitting it as a task in the API, it will get validated to ensure it has a name, a `to<sink>` and either an `every` or `cron`. Does that change your thinking at all?

**Comment by nathanielc** [comment]
Yes they do seem optional. I just wanted to validate that assumption. 

The task name was the one I wasn't sure about. But having validation that requires it in the task service makes sense. For a generic query the task name is optional, it is no longer optional once you want to create a task out of the query.

**Comment by nathanielc** [comment]
#157 adds option support to the AST, we still need to add option support to the interpreter.
