### ISSUE TITLE
Add support for a histogram composite data type.

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#241]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#325  

From the spec:

### Composite data types

A composite data type is a collection of primitive data types that together have a higher meaning.

#### Histogram data type

Histogram is a composite type that represents a discrete cumulative distribution.
Given a histogram with N buckets there will be N columns with the label `le_X` where `X` is replaced with the upper bucket boundary.

**Comment by nathanielc** [comment]
This has been added as part of the histogram and histogramQuantile functions.
