### ISSUE TITLE
Parse duration literals

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#253]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#311  

From the spec:

A duration literal is a representation of a length of time.
It has an integer part and a duration unit part.
Multiple duration may be specified together and the resulting duration is the sum of each smaller part.

    duration_lit        = { int_lit duration_unit } .
    duration_unit       = "ns" | "u" | "µ" | "ms" | "s" | "m" | "h" | "d" | "w" .

| Units    | Meaning                                 |
| -----    | -------                                 |
| ns       | nanoseconds (1 billionth of a second)   |
| us or µs | microseconds (1 millionth of a second)  |
| ms       | milliseconds (1 thousandth of a second) |
| s        | second                                  |
| m        | minute (60 seconds)                     |
| h        | hour (60 minutes)                       |
| d        | day (24 hours)                          |
| w        | week (7 days)                           |

Durations represent a fixed length of time.
They do not change based on time zones or other time related events like daylight savings or leap seconds.

Examples:

    1s
    10d
    1h15m // 1 hour and 15 minutes
    5w

**Comment by aanthony1243** [comment]
@adamperlin there's a related issue for this, we need to remember to link them.

**Comment by adamperlin** [comment]
Also see #287

**Comment by nathanielc** [comment]
See #657
