### ISSUE TITLE
Parse float literals

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#254]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#310  

From the Spec

A floating-point literal is a decimal representation of a floating-point value.
It has an integer part, a decimal point, and a fractional part.
The integer and fractional part comprise decimal digits.
One of the integer part or the fractional part may be elided.

    float_lit = decimals "." [ decimals ] |
        "." decimals .
    decimals  = decimal_digit { decimal_digit } .

Examples:

    0.
    72.40
    072.40  // == 72.40
    2.71828
    .26

**Comment by aanthony1243** [comment]
@adamperlin we can write a test for this too.  Put the expected output in out.csv  even if the current engine doesn't produce that output.

**Comment by mark-rushakoff** [comment]
I'm pretty sure we parse float literals now.
