### ISSUE TITLE
Define syntax for directives

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#257]
From ifql created by [mark-rushakoff](https://github.com/mark-rushakoff) : influxdata/ifql#305  

This isn't about implementing any particular [directive](https://en.wikipedia.org/wiki/Directive_(programming)), but defining how to state a directive in IFQL. 

Directives specify intent of how the particular IFQL script is run. For instance, if you were writing a downsampling job in IFQL, you could use crontab syntax to specify how often it should run. As another example, there could also be a "strict" directive that disallows overwriting or shadowing universal variable.

As a strawman proposal, I suggest that there is a new function `directive` that takes a single map argument. The directive must be the first expression in the file.

```
directive(d: {
  cronSchedule: "0 0 * * *", // Run every day at midnight.
})

from(db: "my_db") |> ...
```

Some preset directives, like the "strict" suggestion would be standard across IFQL. Other directives, like `cronSchedule` in the example, would only take effect on certain IFQL execution engines.

**Comment by mark-rushakoff** [comment]
Superseded by the other issues for Options (#24, etc.).
