### ISSUE TITLE
Formalize concept of Block Key

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#263]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#290  

Currently a block is uniquely identified by this interface:

```
type BlockMetadata interface {
	Bounds() Bounds
	Tags() Tags
}
```

This means that blocks are identified by their time bounds and their tag bounds.

 Knowing what the block key is for a given operation within a query is helpful since it dictates how the data is partitioned an those which datasets the operations operate on.

**Comment by aanthony1243** [comment]
This is now formally in the spec.md document
