### ISSUE TITLE
Queries seem to do an implicit group by *

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#275]
From ifql created by [nhaugo](https://github.com/nhaugo) : influxdata/ifql#251  

curl -X POST --data-urlencode 'q=from(db: "telegraf") |> filter(fn: (r) => r["_measurement"] == "cpu" AND r["_field"] == "usage_user") |> range(start:-10m) |> sum()' http://localhost:8093/query
cpu,cpu=cpu-total,host=telegraf-getting-started usage_user=44.05378747905962 1518618660000000000
cpu,cpu=cpu0,host=telegraf-getting-started usage_user=44.25384527425372 1518618660000000000
cpu,cpu=cpu1,host=telegraf-getting-started usage_user=42.53973183126645 1518618660000000000
cpu,cpu=cpu2,host=telegraf-getting-started usage_user=47.368615374332535 1518618660000000000
cpu,cpu=cpu3,host=telegraf-getting-started usage_user=41.94216362968877 1518618660000000000

Without a group by, it seems this should return a single value

**Comment by aanthony1243** [comment]
we do have an implicit key for queries that don't use group() or window()
