### ISSUE TITLE
Inconsistent results with filter function

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#277]
From ifql created by [pauldix](https://github.com/pauldix) : influxdata/ifql#249  

Here are two examples that I would expect to return the same results:

```
from(db:"mydb")
  |> filter(fn: (r) => r.host == "server0")
  |> last()
```

```
from(db:"mydb")
  |> filter(fn: (r) => {return r.host == "server0"})
  |> last()
```

When run using the IFQL command, the first example returns only blocks that have values matching the filter function. The second example returns those same blocks, but also an empty block for every series that doesn't match the filter function.

**Comment by aanthony1243** [comment]
@adamperlin this doesn't necessarily need a formal test, but can you verify if this is still true and report back here?  Note that either behavior above is OK as long as it is the same for both queries.

**Comment by adamperlin** [comment]
Both queries now return the exact same data
