### ISSUE TITLE
Planner push down rule cannot distinguish parents vs siblings

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#282]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#244  

The planner currently has the concept of a push down rule, which searches for a parent node that has certain features and applies it spec to the parent. If the push down rules encounter a parent that already has those features is duplicates it assuming that a sibling placed those features there and that it can simply overwrite them in a copy. This assumption is not always valid. 

For example:

```
from(db:"telegraf")
    |> range(start:-2m)
    |> group(by:["host"])
    |> last()
    |> group()
    |> sum()
```

The logical plan for this query becomes:

```
logical plan digraph PlanSpec {
from[id="f3647f70-0913-575b-b5da-c96bcf7126d8"];
from->range;
range[id="391ba4b6-4fce-5f25-966c-496a2dfa8a92"];
range->group;
group[id="19250457-facd-5cc9-8c8f-342c59cab1bc"];
group->last;
last[id="0a757bfb-2a06-51c7-a6de-18fa8864675f"];
last->group;
group[id="6ca0b87e-5b78-5b39-9969-6f86e87c4f7c"];
group->sum;
sum[id="c4d9771e-af5e-5f3e-b5cf-68e10ccd052f"];
}
```

After the `range, group, last` procedures have been pushed down the physical plan looks like this:

```
logical plan digraph PlanSpec {
from[id="f3647f70-0913-575b-b5da-c96bcf7126d8"];
from->group;
group[id="6ca0b87e-5b78-5b39-9969-6f86e87c4f7c"];
group->sum;
sum[id="c4d9771e-af5e-5f3e-b5cf-68e10ccd052f"];
}
```

Then things break. The planner sees the `group` and `from` nodes and thinks it can push down `group` if I duplicates `from` first.  This is not valid because the state of `from` is a result of the parents of `group` not its siblings.

The broken plan results in this panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x697893]

goroutine 38 [running]:
github.com/influxdata/ifql/query/plan.(*planner).Plan(0xc420239230, 0xc420399700, 0x0, 0x0, 0x1298738d, 0xed2100294, 0x0, 0xc420400090, 0xc420040e18, 0x7c3624)
        /home/nathanielc/projects/ifql/src/github.com/influxdata/ifql/query/plan/physical.go:134 +0x8d3
github.com/influxdata/ifql/query/control.(*Controller).processQuery(0xc420400000, 0xc420510000, 0xc42006f380, 0xc4204000d8, 0x0)
        /home/nathanielc/projects/ifql/src/github.com/influxdata/ifql/query/control/controller.go:192 +0x2b8
github.com/influxdata/ifql/query/control.(*Controller).run(0xc420400000)
        /home/nathanielc/projects/ifql/src/github.com/influxdata/ifql/query/control/controller.go:173 +0x2e5
created by github.com/influxdata/ifql/query/control.New
        /home/nathanielc/projects/ifql/src/github.com/influxdata/ifql/query/control/controller.go:61 +0x285

```

**Comment by cjek420** [comment]
An other issue with this is that the sum spec is reset, changing ReAggregateSpec to

func (s *SumProcedureSpec) ReAggregateSpec() plan.ProcedureSpec {
	return s.Copy()
}

avoids the problem.

**Comment by nathanielc** [comment]
We should add a test case for this that is failing and skip it.

**Comment by adamperlin** [comment]
@nathanielc we can't easily write a test for this right now given that all `from` operations in the test framework are `fromCSV` so these pushdowns won't occur.

**Comment by pauldix** [comment]
We need to update the test framework to work with other from sources that
have their readers mocked out. I'll need this for testing the fromProm
source.
