### ISSUE TITLE
Wire up where on streams

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#345]
From ifql created by [pauldix](https://github.com/pauldix) : influxdata/ifql#12  

Currently, the expression in `where` function calls is pushed down to the storage engine. It should also work on streams so the query executor needs to be able to evaluate where expression as the data comes in. Will this require differentiating between batch jobs and streams?

@nathanielc

**Comment by aanthony1243** [comment]
@nathanielc I believe this is a non-issue that is solved by filter()  now?

**Comment by nathanielc** [comment]
Yes, closing. We will need to determine how to push down `filter` predicates when we have streaming support. But until then this issues is not doing much.
