### ISSUE TITLE
transpiler filter by tag creates wrong query filter spec

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/platform#355]
Example query: 
https://github.com/influxdata/platform/blob/master/query/querytest/test_cases/filter_by_tags.influxql
`select io_time from testdb..diskio where "name" = "disk0"`

relevant portion of spec: 
&query.Operation{ID: query.OperationID("filter1"), Spec: &functions.FilterOpSpec{Fn: &semantic.FunctionExpression{Params: []*semantic.FunctionParam{&{Key: &semantic.Identifier{Name: "r"}}}, Body: &semantic.BinaryExpression{Operator: s"==", Left: &semantic.MemberExpression{Object: &semantic.IdentifierExpression{Name: "r"}, Property: "name"}, **Right: &semantic.MemberExpression{Object: &semantic.IdentifierExpression{Name: "r"}, Property: "disk0"}}}}}**

should be: 
&query.Operation{ID: query.OperationID("filter1"), Spec: &functions.FilterOpSpec{Fn: &semantic.FunctionExpression{Params: []*semantic.FunctionParam{&{Key: &semantic.Identifier{Name: "r"}}}, Body: &semantic.BinaryExpression{Operator: s"==", Left: &semantic.MemberExpression{Object: &semantic.IdentifierExpression{Name: "r"}, Property: "name"}, **Right: &semantic.StringLiteral{Value: "io_time"}}}}**

**Comment by jsternberg** [comment]
Can you include the test case for this and the relevant influxql query?

**Comment by jsternberg** [comment]
The proper query is:

```
select io_time from testdb..diskio where "name" = 'disk0'
```

This is a standard confusing behavior in influxql that will luckily not be an issue entirely in flux. But the generated query is correct.
