### ISSUE TITLE
Move query/test_cases to the functions package to make them easier to find 

### ISSUE THREAD

**Issue by nathanielc** [influxdata/platform#367]
Also rename test_cases to testdata to follow Go convention.

**Comment by adamperlin** [comment]
Just the `test_cases` or the entire `querytest` package?

**Comment by nathanielc** [comment]
Just the test_cases. The idea is that everything including tests exists in the `functions` package for all functions. Since these tests are testing the functions directly lets move the tests to the functions package. We should probably move the `query_test.go` code to `functions` to accompany the tests. But the rest of the test helps in querytest should remain.

**Comment by nathanielc** [comment]
Also we need to consider what tests look like if they are part of the Flux language. For example maybe their is a `test()` method in Flux that drives these tests.
