### ISSUE TITLE
Query controller needs a Shutdown method

### ISSUE THREAD

**Issue by jsternberg** [influxdata/platform#385]
The query controller needs a way to shutdown analogous to the `Shutdown` method for http servers. It should take a context and should signal the run method to stop accepting new queries. If the context passed in is done, then it should do a hard shutdown and cause the existing queries to error and force the run goroutine to shut down.

**Comment by mark-rushakoff** [comment]
Fixed in https://github.com/influxdata/flux/pull/258.
