### ISSUE TITLE
platform.ID used in testing should have the same number of bytes as snowflake IDs

### ISSUE THREAD

**Issue by fntlnz** [influxdata/platform#413]
Actually, `platform.ID` s used in services are using some random names, see https://github.com/influxdata/platform/blob/master/testing/bucket_service.go#L58.

Since the testing package is used by multiple implementations that are expecting a specific format for `plaftform.ID`s and can make assumptions about it, like storing them in an efficient way, having testing `platform.ID`s that do not respect certain constraints makes things inconsistent accross boundaries.

Reference: https://github.com/influxdata/platform/blob/24b2fbfd95bb87a5f7beb591f8684333d0361021/snowflake/id.go#L30

**Comment by leodido** [comment]
Can close when #442 will be merged.

**Comment by mark-rushakoff** [comment]
#442 was merged a while ago.
