### ISSUE TITLE
Default retention period is '0s'

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#419]
There are few clarifications needed:
- should retention Period be a mandatory parameter when creating a bucket?
- Currently retention period is not a mandatory param. If it is not specified then it default to '0s'. What should be the default RP?

> influx bucket create -n "test3" -o "s"
ID			               Name	Retention	Organization	OrganizationID
02559e3eb5b3c000	test3	0s		                 s		02555e6d7cb3c000

**Comment by pauldix** [comment]
Retention period should not be required. If left unspecified the retention period is to keep data forever `0s`.
