### ISSUE TITLE
Create benchmarks for the parser

### ISSUE THREAD

**Issue by jsternberg** [influxdata/platform#433]
We should create and run benchmarks on the parser for various different queries. This will be slightly more difficult as we should have these benchmarks run on a variety of different queries.

One thing that we did in influxdb was to have a listing of all of the queries we expected to compile and which ones we expected to fail without necessarily caring about the results. We can create that same list (or using the ones in querytest is probably better) and run the benchmarks on all of those.

For the initial version of this, I would test the parser against all of the flux files in querytest.

**Comment by nathanielc** [comment]
The parser has benchmarks
