### ISSUE TITLE
Make ResultIterator.Cancel idempotent

### ISSUE THREAD

**Issue by nathanielc** [influxdata/platform#449]
By allowing the Cancel method to be called multitple times we allow consumers of the type to simply `defer r.Cancel()` whenever they create a new result iterator. That way we simplify the logic of ensuring its resources are freed.
See #430

**Comment by adamperlin** [comment]
@nathanielc is this issue being addressed currently?

**Comment by nathanielc** [comment]
@adamperlin Yes, it became part of #505
