### ISSUE TITLE
query/control: no way to shut down a Controller

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/platform#450]
While writing a test that instantiated a new control.Controller, I noticed that there is no way to shut down a Controller returned from New(). New calls c.run() and the instance can't be garbage collected because there is no way for the run method to return.

https://github.com/influxdata/platform/blob/39569cef9d232e38d28a2433c69e0da2214c485b/query/control/controller.go#L174-L210

To aid in testing, where it's possible many Controller instances may be created, the Controller should have a Shutdown or Close method that stops the `run` goroutine and frees any other appropriate resources.

**Comment by adamperlin** [comment]
See #385

**Comment by mark-rushakoff** [comment]
Thanks, didn't see that issue. Closing as duplicate of #385.
