### ISSUE TITLE
Querying data using influxQL returns an error

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#456]
Using the following request to query the data using influxQL returns an error (I was using the latest master as of 07/23/18):
> unsupported query type influxql (error reference code: 1)

Request: 
> requests.post('http://localhost:9999/query?org=test-org', params='q=select * from test-bucket', headers={"Authorization":"Token <TOKEN>"})

Headers:
> 'X-Request-Id': '3d7d4b76-8ead-11e8-8002-000000000000', 'Request-Id': '3d7d4b76-8ead-11e8-8002-000000000000', 'Content-Length': '0', 'X-Influx-Error': 'unsupported query type influxql (error reference code: 1)', 'Date': 'Mon, 23 Jul 2018 19:18:54 GMT', 'Content-Type': 'application/json', 'X-Influx-Reference': '1'}

**Comment by gshif** [comment]
With the latest build as of 07/20/18 The different error is being returned, looks like the `-` is not being liked by the query - `found -, expected ; at line 1, char 19 (error reference code: 1)`:
- Request:
> requests.post('http://localhost:9999/query?org=test-org-1', params='q=select * from test-bucket-1', headers={"Authorization":"Token kg-XuDdFAy4fOoju4kR0mH3noJZhO-pdaCrJhBaAEhSyMsUO6iuX1wnUn_40RZpZrHWKHTwqvltgxLNI5ElG7A=="})

- Headers:
> {'X-Request-Id': '8d8ff107-9432-11e8-8002-000000000000', 'Request-Id': '8d8ff107-9432-11e8-8002-000000000000', 'Content-Length': '0', **'X-Influx-Error': 'found -, expected ; at line 1, char 19 (error reference code: 1)'**, 'Date': 'Mon, 30 Jul 2018 19:55:47 GMT', 'Content-Type': 'application/json', 'X-Influx-Reference': '1'}

**Comment by jsternberg** [comment]
This has been fixed.
