### ISSUE TITLE
Querying data using gateway API returns 404

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#457]
The below request returns status code `404`
requests.post('http://localhost:9999/v1/query?org=test-org', params='q=from(bucket:"test-bucket")', headers={"Authorization":"Token <TOKEN>"})
@goller , If you are not the right person for the issue, please reassign. Thanks

**Comment by goller** [comment]
Hey @gshif, this is a known issue.  We don't have the flux query handler connected to the idpd process yet.

**Comment by goller** [comment]
@gshif this is now fixed.  Try out `/v2/query`
