### ISSUE TITLE
make filter query params explicit

### ISSUE THREAD

**Issue by desa** [influxdata/platform#469]
Currently filtering query params are implicit and not distinguishable from other query params

e.g. `/v2/users?orgID=1&offset=10`

This can be confusing, instead we propose doing something like [AWS](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html) and having explicit reference to filtering in the query param like `/v2/users?filter[orgID]=1&offset=10`.

**Comment by goller** [comment]
@desa I'd rather not do this.  If anything I think our filters should become more simple.  I don't want to see filters become their own domain specific language.

Additionally, we'll be changing the API to be resource scoped by organization at some point for that particular example.

**Comment by desa** [comment]
Sounds good. Just a thought that came up when gianlucca and I talked.
Wanted to write it down 👍

**Comment by desa** [comment]
not relevant
