### ISSUE TITLE
Errors are being truncated

### ISSUE THREAD

**Issue by gshif** [influxdata/platform#530]
Running a following request, for example, will return an error that is truncated:
> curl -i -X POST  "http://localhost:9999/v1/tasks" -d '{"organization":"0268be95082dc000", "name":"second name", "flux":"option task = {name:\"first name\", cron:\"* * * * *\"}"}'

Returns:
> **X-Influx-Error: rpc error: code = Unknown desc = missing required fields to crea**

**Comment by mark-rushakoff** [comment]
#537 adjusted the truncation limit from 64 bytes to 256. Some messages will still be truncated, but I anticipate very few errors will be that long.
