### ISSUE TITLE
Consider renaming type casting functions

### ISSUE THREAD

**Issue by desa** [influxdata/platform#543]
Currently the type casting functions in flux are prefixed with `to`. So we have things like `[toTime](https://github.com/influxdata/platform/tree/master/query#totime)`. I think this may be confusing since we'll have other functions like `to` for writing to influxdb or `toKafka` for writing kafka.

**Comment by nathanielc** [comment]
See we plan to do this, it is a bullet point on this issue #415

**Comment by desa** [comment]
Closing issue
