### ISSUE TITLE
Ensure every function in the query spec has an example

### ISSUE THREAD

**Issue by jsternberg** [influxdata/platform#546]
Every function should have a working example that is possible with the default telegraf/influxdb/fluxd setup described in the query readme file.

Many of these examples can be taken from the removed lines in the query readme. We're removing a lot of those examples in the readme so the readme itself is relatively easy to read, but we should either move the example to the query spec or create a new example that we know works.

It would also be good to ensure that the readme examples are included as query tests too if we can do that.

**Comment by nathanielc** [comment]
With this one I am interested in what people think with the difference between Flux functions and query Operations. Right now the SPEC lays out the details in the `Operations` section, when we add Flux examples is that still appropriate? Or should we use the built in functions section for the examples and move the descriptions to there? And then just have the operations refer back to the functions docs and note any differences?

**Comment by jsternberg** [comment]
I think we should open up a new issue for the above question. I think that #547 is probably more appropriate for the above.
