### ISSUE TITLE
Add the ability to manage orgs, users, and buckets in the UI

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#568]
as a ui user
with admin permissions or higher
when i view the organization management page in the UI
then i would like to be able to manage my organization including the users and buckets

**Comment by alexpaxton** [comment]
What entails managing these things? I’m guessing for users and orgs it’s similar to what we have now. No idea what goes into bucket management

**Comment by russorat** [comment]
@alexpaxton check out the swagger for managing buckets to get an idea of what you can do: https://github.com/influxdata/platform/blob/master/http/swagger.yml#L1087
