### ISSUE TITLE
task: always set `now` option when executing a task

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/platform#572]
Currently we are not setting the `now` option on tasks that we execute. This means that relative times in the Flux script won't necessarily be aligned with the user's intent. We should always set the `now` option to reflect the actual scheduled time, so that it isn't inferred during remote execution.

In order to set `now` effectively, we need to pass a query Spec rather than a query string, which means we also need to adjust the QueryService interface that the Executor uses.

**Comment by lyondhill** [comment]
closed by https://github.com/influxdata/platform/pull/590
