### ISSUE TITLE
ci: use Circle 2.0 workflow to run JS and Go tests in parallel

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/platform#599]
Currently circle.yml just runs `make test` which builds some dependencies, then runs the JS tests, then runs the Go tests. We should be able to speed this up a bit with a [Circle Workflow](https://circleci.com/docs/2.0/workflows/) to run some things in parallel, but this means we would need to run more granular steps than `make test`.

/cc @nathanielc who probably knows the most about our Makefile.

**Comment by nathanielc** [comment]
Yeah, I think we should have two targets `test-js` and `test-go` then the `test` target just runs both. CircleCI can call them separately in parallel etc.
