### ISSUE TITLE
api: update schema for task Run

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/platform#617]
Runs should include task IDs.

We probably don't need `queuedAt`, as the scheduling implementation doesn't queue and pull; it executes as soon as a run-slot is free and the schedule is due to run. Maybe "lag" would be more appropriate (e.g. it was scheduled to run at 1 PM exactly but started running 100ms after). But it's not clear what lag would mean on retries or re-runs of historical time ranges.

I'm not sure what `startTime` and `stopTime` are, as they don't have a description in the swagger. I don't think `startTime` is the `now` value of a run, but we should report that.

**Comment by jademcgough** [comment]
`startTime` and `stopTime` would be a record of when the run began and ended (since the start may be different from when the task was scheduled to run). I'm happy to change the swagger/API to whatever makes the most sense.

**Comment by mark-rushakoff** [comment]
For now, I'd propose

```go
type Run struct {
  ID ID  `json:"id,omitempty"`

  // ID of the task this run belongs to.
  TaskID ID `json:"taskId"`  
  
  // String enum for status, as currently defined.
  Status    string `json:"status"`

  // The "now" time of the run, i.e. the scheduled time. I'm open to a better name for this field.
  // We're only allowing seconds-granularity, so a plain RFC3339 timestamp makes sense,
  // but if it needs to be RFC3339Nano for consistency, I'm okay with that.
  Now string `json:"now"`

  // When run started executing. RFC3339Nano timestamp.
  StartedAt  string `json:"startedAt"` 
 
  // When run finished executing, regardless of success or failure. RFC3339Nano timestamp.
  FinishedAt  string `json:"finishedAt,omitempty"`

  // Link to the full logs for the run, as currently defined.
  Log       Log    `json:"log"`
}
```

**Comment by mark-rushakoff** [comment]
Maybe #613 means we do need to keep the QueuedAt field. Runs that happen "naturally" aren't really queued, but manual requests or re-runs do have the notion of a queue. I need to think some more on this.

**Comment by mark-rushakoff** [comment]
After a technical discussion on how we're going to approach #613, I'm updating my proposed schema. This renames `now` to `scheduledFor`, and adds a `requestedAt` field which is similar to the intent of `queuedAt`.

```go
For now, I'd propose

```go
type Run struct {
  ID ID  `json:"id,omitempty"`

  // ID of the task this run belongs to.
  TaskID ID `json:"taskId"`  
  
  // String enum for status, as currently defined.
  Status    string `json:"status"`

  // The target "now" time of the run, i.e. the scheduled time.
  // We're only allowing seconds-granularity, so a plain RFC3339 timestamp makes sense,
  // but if it needs to be RFC3339Nano for consistency, I'm okay with that.
  ScheduledFor string `json:"scheduledFor"`

  // When run started executing. RFC3339Nano timestamp.
  StartedAt  string `json:"startedAt"` 
 
  // When run finished executing, regardless of success or failure. RFC3339Nano timestamp.
  FinishedAt  string `json:"finishedAt,omitempty"`

  // When a run was manually requested.
  // Only applies to manual re-runs of a single run or a time range.
  // Field is not present for runs that occur "naturally" as time advances forward and schedule is met.
  RequestedAt string `json:"requestedAt,omitempty"`

  // Link to the full logs for the run, as currently defined.
  Log  Log `json:"log"`
}
```
