### ISSUE TITLE
Make transpiler query handler accept the same parameters as the influxdb 1.x httpd service

### ISSUE THREAD

**Issue by jsternberg** [influxdata/platform#65]
The transpiler query handler needs to expose the same interface as the influxdb 1.x httpd service.

**Comment by pauldix** [comment]
Please make sure to read through: https://github.com/influxdata/idpe/pull/674 to make sure those requirements are captured.

**Comment by jsternberg** [comment]
Split this into #122, #123, and #124.

There's also the chunking parameters, but we're going to punt on those for now since they aren't essential to making the `influx` CLI work from 1.x.
