### ISSUE TITLE
Window function should create empty windows for the procedure bounds

### ISSUE THREAD

**Issue by nathanielc** [influxdata/platform#669]

**Comment by adamperlin** [comment]
@nathanielc would you mind providing a bit more context about what needs to be done here?

**Comment by nathanielc** [comment]
@adamperlin Now that procedures have bounds the window node can produce a window for all windows that intersect the bounds for the window procedure. This means a few things:

* We need to validate that window transformations have bounds, it is an error if they do not. This can be done in the window transformation itself, it does not need to be part of the planner as it is specific to window.
* We need to produce a table for each window that intersects the bounds.

The second part is the real meat of the work. 

Before I jump into some details of how I expect this to work, first some background on the window transformation. The window transformation is a special kind of group by. The group by node just takes input tables and assigns each input record to its output table based on the defined grouping columns. Flux uses the concept of a group key to manage groups. So to group by host, Flux simply looks at the value of the `host` column and assigns records to tables where each table represents a single host. In other words all data for a single host lives in a single table. 

The window function is a special grouping function, it groups by time and it can assign input records to multiple output tables (overlapping windows). The window node adds/updates the _stop, _start columns on the table and adds them to the group key. This way "windows" in Flux are represented as separate tables, where each table represents a given window and any other group columns.

For example given the group by host example, after windowing there will be N*M output tables, where N is the number of input tables (i.e number of hosts) and M is the number of windows that fit in the bounds.

Currently the implementation just assigns each record to its set of output tables given the windows that individual record would land in. We need to change that behavior to output tables even if no record would land in the table, so long as the window of the table intersects the bounds.

All that said I expect the logic will go something like this:

1. Given the window parameters (every, period etc) and the window bounds, compute a list of all windows that intersect the window bounds.
2. For each input table, create a group key that consists of the new _start and _stop columns for all the windows computed in step 1.

Creating a table is idempotent in Flux, so if we duplicate that work I am not worried about it. Meaning you  can apply step 2 for every input table regardless of what input tables you have already processed. 

In general I expect M to be small, i.e. 1000s of windows will be rare, so keeping the entire window list in RAM should be fine. When its not we can optimize for that case later. :)

**Comment by pauldix** [comment]
@nathanielc it's worth mentioning that this strategy caused real problems in earlier versions of InfluxQL. It wasn't uncommon for users to do something silly like selecting 2 years worth of data and grouping by `1s` intervals creating millions of windows. It's also common for users to do a bunch of windows where they expect many of them to be empty and not show up in the result. Just something to think about.

**Comment by nathanielc** [comment]
@pauldix Thanks! We have decided to make creating empty windows optional and off by default. This way if you need the behavior you can get it otherwise it won't be there to mess you up if you are not thinking about it.
