### ISSUE TITLE
Proposal:  unify argument parsing and function signatures using struct tags.

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/platform#676]
problem:  currently it's the burden of the implementor to make sure that all arguments that are parsed from `query.Arguments` are also part of the declared `query.Signature`.   No validation step is taken to ensure this, which may cause problems for some function helpers such as the `BucketAwareOperationSpec`.  

solution:  rather than implementing a validator, ensure that only variables declared in the query.Signature are parsed from the parser: 

`arguments.ParseSignature(&signature)` 

Also discussed:  this may also have an implication on our type system when it's implemented.   A consensus about the design is that specifying the signature and parsing the arguments should be tightly  coupled to prevent the current situation where the signature has no impact on parsing and may become inconsistent with the true implementation of the function.

**Comment by nathanielc** [comment]
The need for this will be moot once https://github.com/influxdata/flux/pull/298 is in place.
