### ISSUE TITLE
Support all dialects in the query endpoint

### ISSUE THREAD

**Issue by fntlnz** [influxdata/platform#680]
Support all dialect responses for the source query endpoint so that even if we call a v2 influxql we can specify either a `csv` or an `influxql` dialect for example.

This is due only for v2 for `influxql` since for v1 it's the influxdb daemon, for v1 we need to ensure that `fluxd` is supporting all the dialects `csv` and `influxql` dialect.

Summary:

Note: some of those are already natively implemented in the backend, while some others needs to be changed in format when calling them in the Proxy Query Source implementations.

- [x] v1 influxql should support the `influxql` dialect
- [ ] v1 flux should support `csv` and `influxql` dialect
- [ ] v2 influxql should support `csv` and `influxql` dialect
- [ ] v2 flux should support `csv` and `influxql` dialect

**Comment by goller** [comment]
Hey @fntlnz we only need to support CSV dialect for now.
