### ISSUE TITLE
Switch this repository to use go modules

### ISSUE THREAD

**Issue by jsternberg** [influxdata/platform#703]
Go 1.11 is now officially released and Go modules are in. It would be good for us as a prominent Go project to begin using modules as soon as we can so we can help with filing bugs and finding issues with our own workflow. We're going to need to do it eventually so we may as well do it sooner rather than later so we aren't stuck figuring out how to do this after modules are fully supported.

We also need to do this first in our open source repository before we attempt to do the same in our closed source version since the closed source one will be more complicated and uses this repository as a dependency.

**Comment by mark-rushakoff** [comment]
Done in #735.
