### ISSUE TITLE
Refactor transpiler interface

### ISSUE THREAD

**Issue by jsternberg** [influxdata/platform#73]
The transpiler interface needs to be refactored so the result encoder is part of the interface somehow. The result encoder needs information about the query that is performed during transpilation to output the correct format so we need to figure out a generic way to create an interface for that.

There are two reasons in particular why the encoder needs information about the query it is transforming.

1. The ordering and naming of columns. IFQL currently has the columns as unordered. This is likely changing (#72), but it is still likely not going to be possible to have multiple columns with the same name which would be needed to transpile an influxql query. So we're going to need some way to map the values from the ifql response to influxql as part of a final step.
2. We will need to differentiate between tags and fields and when both are used. We cannot use a keys presence in the partition key as proof that it's a tag because it may not be! It is also possible to write an influxql query where a tag is returned both in the tags section and in the values section.

Both of these are likely implausible to add into ifql. In all honesty, neither of the features is very useful and are likely mistakes in how a person builds a query. At the same time, we should still support them in the transpiler.

So the interface for the transpiler needs to be changed so the encoding is part of the transpile interface in some way.

**Comment by nathanielc** [comment]
> we need to figure out a generic way to create an interface for that.

I don't think the transpiler interface needs to change. If you need to couple transpiling and encoding you can do that here https://github.com/influxdata/platform/blob/master/http/transpiler_handler.go#L48. There is no need to couple them for all transpilation, just influxql transpiliation. 

The idea would be to create a new InfluxQL encoder for each InfluxQL transpile request.

**Comment by jsternberg** [comment]
This is no longer relevant with the query service refactor in #505.
