### ISSUE TITLE
Design how ShowDatabasesStatement ShowRetentionPoliciesStatement work for 2.x

### ISSUE THREAD

**Issue by nathanielc** [influxdata/platform#769]
How we map these 1.x queries back to 2.x concepts?

We could use a `buckets` function that exposes the bucket data. And the transpiler could rewrite the meta queries to consume the buckets function.

**Comment by nathanielc** [comment]
A simple bucket function makes sense and as a source function too. There is already the BucketService interface that will let you enumerate buckets. The storage layers defined BucketLookup since it only needed to lookup a single bucket, the buckets function does not need to use that same interface if it doesn't want to.

What about the retention policy information? Should there be a separate function to get the duration etc of buckets? Or should the normal buckets function return all the data and the transpiler etc, just drops the unwanted columns?

**Comment by aanthony1243** [comment]
Right, i confirmed that we have the functionality to get a list of buckets.  It's just a matter of exposing the right API via the execute.Administration.Dependencies() call.  We could either extend the existing interface, or just provide a new one that has the info we need.  

I think a full info-dump makes sense, and then we can drop what's not needed on the transpiler.  

Do we want to expose this to users?  e.g.  can they call `buckets()`  in `Flux`?

**Comment by nathanielc** [comment]
> Do we want to expose this to users? e.g. can they call buckets() in Flux?

Yes
