### ISSUE TITLE
Add org as a query param to bucket

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#790]

**Comment by gianarb** [comment]
About the `handlePostBucket`, if the organization is required why is not part of the body itself?

**Comment by goller** [comment]
@gianarb 

> About the handlePostBucket, if the organization is required why is not part of the body itself?

I've gone back and forth on this exact issue.  With a parameter we at least make it consistent across the API for the top routes (e.g. /buckets, /write, /query).  This allows us to have links within the response body pointing to other resources scoped within an organization.

**Comment by mark-rushakoff** [comment]
The change in #812 broke, or at least didn't update, the `(*platform/http.BucketService).CreateBucket` method.

My code snippet like

```
	buckets := phttp.BucketService{Addr: *gatewayEndpoint}
	bIn := &platform.Bucket{Name: bucketInName(), OrganizationID: o.ID, RetentionPeriod: time.Hour}
	if err := buckets.CreateBucket(ctx, bIn); err != nil {
		log.Fatalf("failed to create bucket: %v", err)
	}
```

is failing with `09:48:31.049418 failed to create bucket: The "org" is required via query param. (error reference code: 1)`.
