### ISSUE TITLE
Add links to orgs

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#795]

**Comment by desa** [comment]
Similar to https://github.com/influxdata/platform/issues/794 and https://github.com/influxdata/platform/issues/793

The response for a single org is currently
```json
{
  "id": "029964db55094000",
  "name": "m"
}
```
but it should be
```json
{
  "links": {
    "self": "/v2/orgs/:id",
    "buckets": "/v2/buckets?org=m",
    "members": "/v2/orgs/:id/members",
    "...": "..."
  },
  "id": "029964db55094000",
  "name": "m"
}
```

Similarly the response for many orgs is currently
```json
[
  {
    "id": "029964db55094000",
    "name": "m"
  },
  {
    "id": "029965f838c94000",
    "name": "md"
  }
]
```
and should be
```json
{
  "links": {
    "self": "/v2/orgs"
  },
  "orgs": [
    {
      "links": {
        "self": "/v2/orgs/:id",
        "buckets": "/v2/buckets?org=m",
        "members": "/v2/orgs/:id/members",
        "...": "..."
      },
      "id": "029964db55094000",
      "name": "m"
    },
    {
      "links": {
        "self": "/v2/orgs/:id",
        "buckets": "/v2/buckets?org=m",
        "members": "/v2/orgs/:id/members",
        "...": "..."
      },
      "id": "029964db55094000",
      "name": "m"
    }
  ]
}
```

See the [SourceHandler](https://github.com/influxdata/platform/blob/7bbd08798031ccf7f3795df8af53fd4f0f9a048a/http/source_service.go#L25-L62) for reference
https://github.com/influxdata/platform/blob/7bbd08798031ccf7f3795df8af53fd4f0f9a048a/http/source_service.go#L25-L62

**Comment by desa** [comment]
Check the [swagger](https://github.com/influxdata/platform/blob/doc/api/http/swagger.yml) for a complete list of links
