### ISSUE TITLE
Implement macros (template variables) API

### ISSUE THREAD

**Issue by desa** [influxdata/platform#797]
Add `MacroService` and associated HTTP handler that conforms to the specification

https://github.com/influxdata/platform/blob/f437888ee24e812fb8ddaa03468e7acd1103ef91/http/swagger.yml#L18-L147

https://github.com/influxdata/platform/blob/f437888ee24e812fb8ddaa03468e7acd1103ef91/http/swagger.yml#L2973-L3058

Implementation should be similar to the `ViewService` and `ViewHandler`

**Comment by russorat** [comment]
A few comments here:
 - We would like to migrate the new macros to be at the org level, so they aren't tied to a particular dashboard.
 - When importing 1.x dashboards, and connected to a 2.x source, the influxql based temp vars can just error initially. Switching to a 1.x source is the only way they would work.
 - We will need a UI for managing macros. @alexpaxton @mavarius
