### ISSUE TITLE
Jump back into the data upload portion of the onboarding app

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#800]
If a user wants to upload data after they have completed the onboarding step, they should be able to. The goal of this story would be to add a button in the UI which will jump the user back into the same data upload screen found here https://github.com/influxdata/platform/issues/567.

This may make sense to add to the source config area of the app and the data explorer area of the app.

**Comment by alexpaxton** [comment]
I vote to stick this in the config area & data explorer
