### ISSUE TITLE
Convert InfluxDB storage engine metrics to prometheus metrics

### ISSUE THREAD

**Issue by e-dard** [influxdata/platform#885]
As we bring the old storage engine code in from InfluxDB we will want to convert all the the metrics that used to report to the `_internal` database into prometheus metrics, to complement our existing set of metrics.

**Comment by stevebang** [comment]
@e-dard If you haven't seen this, it might be useful -- I created it and added it about two weeks ago, after going through Go code, GitHub issues, and Community postings to get the content.

http://docs.influxdata.com/platform/monitoring/tools/measurements-internal/

Keep me in the loop on this, or even engage me for naming and doc'ing (in code comments and external docs).
