### ISSUE TITLE
Add owners to dashboards

### ISSUE THREAD

**Issue by jademcgough** [influxdata/platform#904]
Here's my brain dump on this:

We currently have `/members` endpoints on `OrgHandler`.

We need both `/members/` and `/owners` endpoints for buckets, dashboards, and organizations (and probably others).

Instead of reimplementing the same endpoints for every service that requires it, it'd be much cleaner to add a handler to `UserResourceMappingService` that handles the endpoints:

`/v1/:resourcetype/:resourceid/members`
`/v1/:resourcetype/:resourceid/members/:memberid`
`/v1/:resourcetype/:resourceid/owners`
`/v1/:resourcetype/:resourceid/owners/:ownerid`

`UserResourceMapping`s don't care about the resource type, they just map a relationship between a user and a resource id, so it should be able to handle these endpoints in a resource type agnostic fashion.

**Comment by desa** [comment]
Might be a bit hard to check the for the `:resourcetype` suffix with how we do routing. What if we made factory that we could reuse in other handlers?

**Comment by jademcgough** [comment]
@desa thanks, yeah, that's a better pattern for this
