### ISSUE TITLE
Add org config endpoint for platform chronograf

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#918]
Add a route for 
`/api/v2/org/:id/config`

And define an associated `OrganizationConfigService` and implement the associated bolt interface to allow users to store and retrieve log viewer org config

**Comment by goller** [comment]
@russorat if log viewer is a kind of view, could these be view specific options?

**Comment by russorat** [comment]
@OfTheDelmer could you help with @goller 's question?

**Comment by goller** [comment]
@russorat @OfTheDelmer and I will have a PR shortly for it.  Basically, we followed the pattern that @121watts and @bthesorceror have for more view types.
