### ISSUE TITLE
Rewrite buildLogQuery for platform 

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#919]
```
  from(bucket: "telegraf/autogen") 
  |> range(start: START, stop: STOP)
  |> filter(fn: (r) => r._measurement == "syslog")
  |> pivot(rowKey:["_time"], colKey: ["_field"], valueCol: "_value")
  |> group(none: true)
  |> sort(cols: ["_time"])
  |> keep(columns: SYSLOG_FIELDS)
```

The current issue with this task is that `appname` or any other column in syslog can be missing and there's not an easy way to specify a default

**Comment by OfTheDelmer** [comment]
With the above query I was trying to replicate the following InfluxQL query

```
SELECT "severity", "timestamp", "message", "facility", "procid", "appname", "host" 
      FROM "telegraf"."autogen"."syslog" 
      WHERE time >= 'START' AND time < 'END' 
      ORDER BY time DESC
```

I initially tried the `fromRows(bucket: "telegraf/autogen")`

```
fromRows(bucket: "telegraf/autogen") 
   |> range(start: -1m) 
   |> filter(fn: (r) => r._measurement == "syslog") 
   |> yield()
Error: failed to create physical plan: invalid time bounds from procedure from: bounds contain zero time
```

I got the above error. However, adding the `pivot` after the `filter` and `range` is the work around I used.

 After grouping the rows I wanted to pipe the through `keep` to try to keep only syslog columns I was interested in `"severity", "timestamp", "message", "facility", "procid", "appname", "host"`.

I used the node script from [https://github.com/bthesorceror/generate-syslog](generate-syslog) to generate log messages which creates syslog messages with a null `appname`. This was causing an error when trying to `keep` a column that was never created. I could get around this using the predicate for of `keep`.

```
|> keep((column) => column == "severity" or column == "timestamp" ...)
```

But, then I would just have to diff table result for each chunk to see when a column was dropped. It would be nice if there was an easy way to say try to select this or set it to `nil` or some default.

----

The weirdest thing about this error is that once I started generating syslog data with an `appname` all queries that started and ended after appname was provided returned results, but those query's for data before that time would fail.

**Comment by OfTheDelmer** [comment]
Trying to run the original influxql query on platform I a 200

![screen shot 2018-09-28 at 5 11 46 pm](https://user-images.githubusercontent.com/4994741/46319580-8321ad00-c5a8-11e8-90c7-4cb04fe29b87.png)

But, I get the following error

```
#datatype,string,string
#group,true,true
#default,,
,error,reference
,invalid type <nil> found in column appname,
```

**Comment by OfTheDelmer** [comment]
@nathanielc I tried out the `set` function for `appname` and agree that overwriting wouldn't be right here. 

Currently, the log viewer pagination fetches consecutive chunks of logs in 30 second intervals as the user scrolls. The first few chunk fetches might be fine but if log viewer fetches a chunk in an interval where `appname` was always a nil value it fails. To my knowledge there nothing special about `appname` being nil as the syslog messages written to telegraf could choose to provide a nil value for  one of the `severity`, `timestamp`, `message`, `facility`, `procid`, `appname`,  or `host` for some interval of time in the logs.
