### ISSUE TITLE
Unify storage engine configuration

### ISSUE THREAD

**Issue by e-dard** [influxdata/platform#955]
We need to unify the storage engine configuration. The result could look like this on the config file:

```toml
[storage]
   ...
   ...
   ...

   [index]
       ...
       ...
```

We need to merge the `tsdb.Config` into the `storage.Config`, and remove the need to inject the `tsdb.Config` into the `tsm1.EngineOptions` struct.

**Comment by zhulongcheng** [comment]
@e-dard   Merge `tsdb.EngineOptions` into `storage.Config` ?

**Comment by zeebo** [comment]
Hey @zhulongcheng, I've been working on this for a day or two. Sorry I didn't put any message in here or assign it.
