### ISSUE TITLE
Add list tasks page

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#957]
as a task builder
with viewer permissions or higher
when i open the platform UI
then i am able to view a page that lists all the tasks i have access to

**Comment by alexpaxton** [comment]
Please use these components to construct the page itself:
https://github.com/influxdata/platform/tree/master/chronograf/ui/src/page_layout/components

And use this component to construct the list view:
https://github.com/influxdata/platform/tree/master/chronograf/ui/src/shared/components/index_views
