### ISSUE TITLE
Add retention service to the storage engine

### ISSUE THREAD

**Issue by e-dard** [influxdata/platform#992]
We need to bring the new retention service into Platform.

**Comment by pauldix** [comment]
Can we not call it a service this time since it's just something that runs on a schedule in the process? I'd rather service mean "something that is network accessible" which is its standard use.

**Comment by e-dard** [comment]
@pauldix I 100% agree and yes I'm going to be renaming it. I just referreed to it as a service as that's the implementation is named 😄
